collectionspace/services

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/build.xml
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/conservation/3rdparty/build.xml
services/conservation/3rdparty/nuxeo-platform-cs-conservation/build.xml
services/conservation/3rdparty/nuxeo-platform-cs-conservation/pom.xml
services/conservation/3rdparty/nuxeo-platform-cs-conservation/src/main/resources/OSGI-INF/README.txt
services/conservation/3rdparty/nuxeo-platform-cs-conservation/src/main/resources/schemas/README.txt
services/conservation/3rdparty/pom.xml
services/conservation/build.xml
services/conservation/client/pom.xml
services/conservation/client/src/main/java/org/collectionspace/services/client/ConservationClient.java
services/conservation/client/src/main/java/org/collectionspace/services/client/ConservationProxy.java
services/conservation/client/src/test/java/org/collectionspace/services/client/test/ConservationAuthRefsTest.java
services/conservation/client/src/test/java/org/collectionspace/services/client/test/ConservationServiceTest.java
services/conservation/client/src/test/resources/log4j.properties
services/conservation/jaxb/pom.xml
services/conservation/jaxb/src/main/java/org/collectionspace/services/ConservationJAXBSchema.java
services/conservation/jaxb/src/main/java/org/collectionspace/services/ConservationListItemJAXBSchema.java
services/conservation/jaxb/src/main/resources/conservation-common.xsd
services/conservation/pom.xml
services/conservation/service/pom.xml
services/conservation/service/src/main/java/org/collectionspace/services/conservation/ConservationResource.java
services/conservation/service/src/main/java/org/collectionspace/services/conservation/nuxeo/ConservationConstants.java
services/conservation/service/src/main/java/org/collectionspace/services/conservation/nuxeo/ConservationDocumentModelHandler.java
services/conservation/service/src/main/java/org/collectionspace/services/conservation/nuxeo/ConservationValidatorHandler.java
services/conservation/service/src/test/java/org/collectionspace/services/test/ConservationServiceTest.java
services/conservation/service/src/test/resources/log4j.xml
services/pom.xml

Awaiting final approval from Megan/community.

CSPACE-6902: Add conservation procedure.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/coreAcquisition.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreGroupObject.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreIntake.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanIn.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanOut.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreObjectExit.jrxml

coreAcquisition.jrxml
coreGroupObject.jrxml
coreIntake.jrxml
coreLoanIn.jrxml
coreLoanOut.jrxml
coreObjectExit.jrxml

CODE-37: add six jrxml files for core reports

---

services/report/3rdparty/jasper-cs-report/src/main/resources/coreObjectExit.jrxml

updated query to display message when no objects are related.

CSPACE-6948

---

README.txt

Adding a reference to the GitHub repos.

NOJIRA: Updating README.txt to reference GitHub repo.

---

services/IntegrationTests/src/test/resources/test-data/xmlreplay/vocabulary/DeleteItemFromPagesOfItems/deleteItemFromSecondPage-vocab.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/vocabulary/DeleteItemFromPagesOfItems/responses/deleteItemFromPagesOfItems.res.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/vocabulary/vocabulary.xml
services/vocabulary/service/src/main/java/org/collectionspace/services/vocabulary/VocabularyResource.java

Fixed issue when deleting term from a very long list.

DRYD-568: Fixed issue when deleting term from a very long list.

---

.gitignore
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/common/src/main/java/org/collectionspace/services/common/ServiceMessages.java
services/common/src/main/java/org/collectionspace/services/common/context/ServiceBindingUtils.java
services/common/src/main/java/org/collectionspace/services/common/security/SecurityInterceptor.java
services/config/src/main/java/org/collectionspace/services/common/config/PropertyItemUtils.java
services/config/src/main/resources/types.xsd
services/report/jaxb/src/main/resources/reports-output-mime.xsd
services/report/service/src/main/java/org/collectionspace/services/report/ReportResource.java
services/report/service/src/main/java/org/collectionspace/services/report/nuxeo/ReportDocumentModelHandler.java

CC-584: Adding 'displayName' field to payload result for endpoint reports/mimetypes.

CC-584: Adding code to pull list of reporting output MIME types.

---

3rdparty/nuxeo/nuxeo-platform-listener/botgarden/pom.xml
3rdparty/nuxeo/nuxeo-platform-listener/botgarden/src/main/java/org/collectionspace/services/listener/botgarden/CreateVersionListener.java
3rdparty/nuxeo/nuxeo-platform-listener/botgarden/src/main/java/org/collectionspace/services/listener/botgarden/DeleteDeadLocationListener.java
3rdparty/nuxeo/nuxeo-platform-listener/botgarden/src/main/java/org/collectionspace/services/listener/botgarden/UpdateAccessCodeListener.java
3rdparty/nuxeo/nuxeo-platform-listener/botgarden/src/main/java/org/collectionspace/services/listener/botgarden/UpdateDeadFlagListener.java
3rdparty/nuxeo/nuxeo-platform-listener/botgarden/src/main/java/org/collectionspace/services/listener/botgarden/UpdateLocationListener.java
3rdparty/nuxeo/nuxeo-platform-listener/botgarden/src/main/java/org/collectionspace/services/listener/botgarden/UpdateRareFlagListener.java
3rdparty/nuxeo/nuxeo-platform-listener/botgarden/src/main/java/org/collectionspace/services/listener/botgarden/UpdateStyledNameListener.java
3rdparty/nuxeo/nuxeo-platform-listener/naturalhistory/src/main/java/org/collectionspace/services/listener/naturalhistory/UpdateFormattedDisplayNameListener.java
3rdparty/nuxeo/nuxeo-platform-listener/reindex/src/main/java/org/collectionspace/services/listener/Reindex.java
3rdparty/nuxeo/nuxeo-platform-listener/reindex/src/main/java/org/collectionspace/services/listener/ReindexSupport.java
3rdparty/nuxeo/nuxeo-platform-listener/updateimagederivatives/src/main/java/org/collectionspace/services/listener/UpdateImageDerivatives.java
3rdparty/nuxeo/nuxeo-platform-listener/updateobjectlocationonmove/src/main/java/org/collectionspace/services/listener/AbstractUpdateObjectLocationValues.java
3rdparty/nuxeo/nuxeo-platform-listener/updateobjectlocationonmove/src/main/java/org/collectionspace/services/listener/UpdateObjectLocationAndCrateOnMove.java
3rdparty/nuxeo/nuxeo-platform-listener/updateobjectlocationonmove/src/main/java/org/collectionspace/services/listener/UpdateObjectLocationOnMove.java
3rdparty/nuxeo/nuxeo-platform-listener/updaterelationsondelete/src/main/java/org/collectionspace/services/listener/UpdateRelationsOnDelete.java
3rdparty/nuxeo/nuxeo-platform-thumbnail/pom.xml
3rdparty/nuxeo/nuxeo-platform-thumbnail/src/main/java/org/collectionspace/services/nuxeo/extension/thumbnail/AddThumbnailUnrestricted.java
3rdparty/nuxeo/nuxeo-platform-thumbnail/src/main/java/org/collectionspace/services/nuxeo/extension/thumbnail/Thumbnail.java
3rdparty/nuxeo/nuxeo-platform-thumbnail/src/main/java/org/collectionspace/services/nuxeo/extension/thumbnail/ThumbnailConverter.java
3rdparty/nuxeo/nuxeo-platform-thumbnail/src/main/java/org/collectionspace/services/nuxeo/extension/thumbnail/UpdateThumbListener.java
services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/UpdateAccessCodeBatchJob.java
services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/UpdateRareFlagBatchJob.java
services/common/pom.xml
services/common/src/main/java/org/collectionspace/services/common/imaging/nuxeo/NuxeoBlobUtils.java
services/common/src/main/java/org/collectionspace/services/nuxeo/listener/AbstractCSEventListenerImpl.java
services/common/src/main/java/org/collectionspace/services/nuxeo/listener/AbstractCSEventPostCommitListenerImpl.java
services/common/src/main/java/org/collectionspace/services/nuxeo/listener/AbstractCSEventSyncListenerImpl.java
services/common/src/main/java/org/collectionspace/services/nuxeo/listener/CSEventListener.java
services/common/src/main/java/org/collectionspace/services/nuxeo/util/ThumbnailConstants.java

Refactored CSpace's event handling classes and interfaces to support both sync and async Nuxeo event handlers.

DRYD-477: Event handler refactor

---

src/main/resources/db/postgresql/upgrade/6.0.0/post-init/05_uoc.sql

Add migration notes for userGroup.
Add command to migration userGroup.userType to userGroup.userInstitutionRole.

DRYD-835: Update UOC migration script: Migrate userGroup.userType

---

src/main/resources/db/postgresql/upgrade/6.0.0/post-init/05_uoc.sql

-- Check to make sure both userType and userInstitutionRole columns exist in userGroup table.
-- Only update when userInstitutionRole IS NULL.

DRYD-835: Update UOC migration script: Add checks for userGroup update

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/build.xml
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/pom.xml
services/transport/3rdparty/build.xml
services/transport/3rdparty/nuxeo-platform-cs-transport/build.xml
services/transport/3rdparty/nuxeo-platform-cs-transport/pom.xml
services/transport/3rdparty/nuxeo-platform-cs-transport/src/main/resources/OSGI-INF/README.txt
services/transport/3rdparty/nuxeo-platform-cs-transport/src/main/resources/schemas/README.txt
services/transport/3rdparty/pom.xml
services/transport/build.xml
services/transport/client/pom.xml
services/transport/client/src/main/java/org/collectionspace/services/client/TransportClient.java
services/transport/client/src/main/java/org/collectionspace/services/client/TransportProxy.java
services/transport/client/src/test/java/org/collectionspace/services/client/test/TransportServiceTest.java
services/transport/jaxb/pom.xml
services/transport/jaxb/src/main/java/org/collectionspace/services/TransportJAXBSchema.java
services/transport/jaxb/src/main/java/org/collectionspace/services/TransportListItemJAXBSchema.java
services/transport/jaxb/src/main/resources/transports-common.xsd
services/transport/pom.xml
services/transport/service/pom.xml
services/transport/service/src/main/java/org/collectionspace/services/transport/TransportResource.java
services/transport/service/src/main/java/org/collectionspace/services/transport/nuxeo/TransportConstants.java
services/transport/service/src/main/java/org/collectionspace/services/transport/nuxeo/TransportDocumentModelHandler.java
services/transport/service/src/main/java/org/collectionspace/services/transport/nuxeo/TransportValidatorHandler.java
services/transport/service/src/test/java/org/collectionspace/services/test/TransportServiceTest.java

Resolves: https://collectionspace.atlassian.net/browse/DRYD-943
* Add modules + impl for transport procedure
* Add TransportResource to jaxrs app
* Create id generator for `transportReferenceNumber`

DRYD-943: Add Transport Procedure

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/insurance/3rdparty/build.xml
services/insurance/3rdparty/nuxeo-platform-cs-insurance/build.xml
services/insurance/3rdparty/nuxeo-platform-cs-insurance/pom.xml
services/insurance/3rdparty/nuxeo-platform-cs-insurance/src/main/resources/OSGI-INF/README.txt
services/insurance/3rdparty/nuxeo-platform-cs-insurance/src/main/resources/schemas/README.txt
services/insurance/3rdparty/pom.xml
services/insurance/build.xml
services/insurance/client/pom.xml
services/insurance/client/src/main/java/org/collectionspace/services/client/InsuranceClient.java
services/insurance/client/src/main/java/org/collectionspace/services/client/InsuranceProxy.java
services/insurance/jaxb/pom.xml
services/insurance/jaxb/src/main/java/org/collectionspace/services/InsuranceJAXBSchema.java
services/insurance/jaxb/src/main/java/org/collectionspace/services/InsuranceListItemJAXBSchema.java
services/insurance/jaxb/src/main/resources/insurances_common.xsd
services/insurance/pom.xml
services/insurance/service/pom.xml
services/insurance/service/src/main/java/org/collectionspace/services/insurance/InsuranceResource.java
services/insurance/service/src/main/java/org/collectionspace/services/insurance/nuxeo/InsuranceConstants.java
services/insurance/service/src/main/java/org/collectionspace/services/insurance/nuxeo/InsuranceDocumentModelHandler.java
services/insurance/service/src/main/java/org/collectionspace/services/insurance/nuxeo/InsuranceValidatorHandler.java
services/pom.xml

Resolves:  https://collectionspace.atlassian.net/browse/DRYD-944
* Add id_generators for insurance and indemnity
* Add implementation for insurance client, jaxb, and service modules

DRYD-944: Create insurance/indemnity procedure

---

src/main/resources/db/postgresql/upgrade/7.0.0/post-init/01_nagpra-nagprareportfiledgroup.sql

@ray-lee  please review.
cc @remillet

DRYD-921: fixed incorrect hierarchy.name for original nagpraReportFiledDate

---

services/iterationreport/client/src/test/java/org/collectionspace/services/client/test/IterationreportServiceTest.java
services/iterationreport/jaxb/src/main/resources/iterationreports_common.xsd

* Use correct identifier in iterationreports_common xsd
* Update tests to use correct id

DRYD-1036: Fix iteration report xsd

---

services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml

Apply refname_displayname_normalizer to objectProductionPlace.
Field uses autocomplete on: place/local

Fcart es mapping update

---

services/report/3rdparty/jasper-cs-report/src/main/resources/object_valuation.jrxml

Just changes an erroneous INNER JOIN to a LEFT OUTER JOIN

DRYD-1170: fix query in object_valuation report

---

services/common/src/main/java/org/collectionspace/services/common/imaging/nuxeo/NuxeoBlobUtils.java

Jira: https://collectionspace.atlassian.net/browse/DRYD-1183
* Track number of derivatives for blobs when adding to the CommonList
* Minor code cleanup
There isn't a test which covers the NuxeoBlobUtils, though I'm not against adding something to at least try and get something here to verify behavior. Otherwise to test what I did was:
* Build CSpace
* Create a media handling resource so that derivatives are generated
* Use curl to get the derivative list, e.g. `curl --user "admin@core.collectionspace.org:Administrator" http://localhost:8180/cspace-services/media/8f86f12b-ae09-4cf3-85d2/blob/derivatives | xmllint --format - | less`

DRYD-1183: Set totalItems and itemsInPage for derivative lists

---

build.properties
pom.xml

This updates the version number to 7.2.0-SNAPSHOT.
This (belatedly) starts the dev cycle for the next release.'
Build and deploy should work without error:
`mvn clean install -DskipTests && ant undeploy deploy`
None.
n/a
@ray-lee ran a successful build.

Start 7.2 dev cycle.

---

services/export/service/src/main/java/org/collectionspace/services/export/ExportResource.java

This updates the ExportResource to filter out restricted fields in the `collectionspace_core` namespace rather than the entire namespace. The set of allowed fields is now the `created{By,At}`, `updated{By,At}`, and `uri`. For namespaces which should have all fields removed, an empty list is provided to indicate the entire part should be removed.
In the export modal, it is possible to selected the created and updated fields for a record, but when getting the results these returned with empty values. In addition, it was requested to be able to export the uri in order to make automated operations easier.
* https://collectionspace.atlassian.net/browse/DRYD-901
* https://collectionspace.atlassian.net/browse/DRYD-1080 
**How …

DRYD-901: Only restrict fields for core namespace

---

services/relation/service/src/main/java/org/collectionspace/services/relation/nuxeo/RelationDocumentModelHandler.java

When creating a relation, this adds a check to ensure that the new relation would not result in a circular hierarchy (`hasBroader` relation) loop. If it would create a circular hierarchy, an error is returned, and the relation is not created.
A circular hierarchy could potentially cause problems when it is not expected, and there doesn't seem to be a use case for it.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1042
For Objects and various authority items:
- Create records: A, B, and C.
- Edit C, and assign it the broader record B.
The save should succeed.
- Edit B, and assign it the broader record A.
The save should succeed.
- Edit A, and …

DRYD-1042: Error on circular hierarchy creation.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/referral.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/referral.xml

* Adds referral report
* Adds xml for registering referral report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1132
* Register the report with collectionspace
* Create an intake with
* entry date, entry method, approval group (all fields), entry note, packing note, current location, current owner (2 persontermgroups + address)
* Create a related collectionobject with
* object name, production date, collection, brief description, object history note, related media
None
No
**Did someone actually …

DRYD-1132: Referral report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/referral.jrxml

This brings in various changes requested from review of the reports:
* Deaccession
* Remove exit quantity
* Remove secondary term name
* Fix additional relations to join using collectionobject
* Increase column headers to prevent truncation of text
* Deed of Gift
* Remove secondary term name
* Basic Object with Computed Location
* Fix join to be on place authority
* Outgoing Loan
* Add loan status
* Referral
* Remove secondary term name 
This changes are coming in from review of the recent reports which were made. These include removal of various fields from the result set (e.g. the secondary term names), and correcting joins which had incorrect assumptions about how the data was related. I noticed some issues as well, …

Report updates

---

services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/contact/service/src/main/java/org/collectionspace/services/contact/nuxeo/ContactValidatorHandler.java

* Add ContactValidatorHandler
Jira: https://collectionspace.atlassian.net/browse/DRYD-1257
This is part of the UCB Bundle Contribution. It adds a new ContactValdidatorHandler.
* Build and run collectionspace
* Create a Person or Organization with Contact Information filled out
None
No
@mikejritter built and ran integration tests

DRYD-1257: UCB ContactValidatorHandler Contrib

---

services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/bonsai/bonsai-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/materials/materials-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml

This adds some additional content and rights management fields to the Elasticsearch index. The rights management fields are not added to the full text index, as this didn't seem like it would be useful.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1381
Create a collectionobject, filling in the following fields:
- Content Description
- Content Person
- Content Organization
- Content Event/Period or Era
- Standardized right statement
- Right statement
- Right statement for reproduction
Issue a query to the ES API that will return the record.
The following fields should appear:
- collectionobjects_common:contentDescription
- …

DRYD-1381: Add content and rights fields to ES index.

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/heldintrust/build.xml
services/heldintrust/client/pom.xml
services/heldintrust/client/src/main/java/org/collectionspace/services/client/HeldInTrustClient.java
services/heldintrust/client/src/main/java/org/collectionspace/services/client/HeldInTrustProxy.java
services/heldintrust/client/src/test/java/org/collectionspace/services/client/test/HeldInTrustServiceTest.java
services/heldintrust/jaxb/pom.xml
services/heldintrust/jaxb/src/main/resources/heldintrusts_common.xsd
services/heldintrust/pom.xml
services/heldintrust/service/pom.xml
services/heldintrust/service/src/main/java/org/collectionspace/services/heldintrust/HeldInTrustResource.java
services/heldintrust/service/src/main/java/org/collectionspace/services/heldintrust/nuxeo/HeldInTrustConstants.java
services/heldintrust/service/src/main/java/org/collectionspace/services/heldintrust/nuxeo/HeldInTrustDocumentModelHandler.java
services/heldintrust/service/src/main/java/org/collectionspace/services/heldintrust/nuxeo/HeldInTrustValidatorHandler.java
services/pom.xml

* Create Held-in-Trust service and test
* Create Held-in-Trust id generator
Jira: https://collectionspace.atlassian.net/browse/DRYD-1358
This adds the Held-in-Trust service as part of the nagpra workflows for 8.1. 
* Rebuild collectionspace with tenants enabled for running the integration tests
* Start collectionspace
* Run the integration test suite
Not sure what will be going on with the UCB Held-in-Trust procedure, might be worth having a discussion about it.
No …

DRYD-1358: Held-in-Trust

---

services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_intent_to_repatriate.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_intent_to_repatriate.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_inventory_completion.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_inventory_completion.xml

* Add Notice of Intent to Repatriate report
* Add Notice of Inventory Completion report
Jira:
* https://collectionspace.atlassian.net/browse/DRYD-1334
* https://collectionspace.atlassian.net/browse/DRYD-1335
These are new reports to help with NAGPRA workflows. 
These are intended to be tested on dev to get feedback on formatting of the detail fields and headers used.
The Notice of Intent to Repatriate report spec relies on terms which have not been added yet. It will need to be updated once the Object Count term lists are updated. …

NAGPRA Workflow Reports

---

build.properties
cspace-ui/anthro/build.properties
cspace-ui/fcart/build.properties
cspace-ui/lhmc/build.properties

* Update ui versions to latest RC
n/a
* Rebuild CollectionSpace with all tenants enabled and ensure the build passes
* The deploy step downloads the latest profiles, so this is necessary for any build to succeed
n/a
No
@mikejritter is building locally

Update UI Versions for latest RC

---

services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/contact_org.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/contact_org.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/contact_person.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/contact_person.xml

* Add contact person report
* Add contact org report
Jiras:
* https://collectionspace.atlassian.net/browse/DRYD-1576
* https://collectionspace.atlassian.net/browse/DRYD-1577
These reports make it easier to get contact information out of the Person and Organization authority records.
* Redeploy the reports for collectionspace, e.g.
```
cd "${SERVICES_ROOT}/services/report/3rdparty"
ant undeploy_report_files
ant deploy_report_files
```
* Create a Person in order to test the Contact Person report
* Create an Organization in order to test the Contact Organization report
None
**Has the application …

Contact Reports

---

build.properties
pom.xml

* Updates build release to 8.1.1
* Updates cspace-ui release in build properties
No jira
This is part of the release process for cspace.
* Build and start collectionspace
None
No
@mikejritter built locally

Update Version to 8.1.1
