collectionspace/services

3rdparty/nuxeo/build.xml
3rdparty/nuxeo/nuxeo-platform-elasticsearch/build.xml
3rdparty/nuxeo/nuxeo-platform-elasticsearch/pom.xml
3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/java/org/collectionspace/services/nuxeo/elasticsearch/CSJsonESDocumentWriter.java
3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/resources/META-INF/MANIFEST.MF
3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/resources/OSGI-INF/deployment-fragment.xml
3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/resources/OSGI-INF/elasticsearch-contrib.xml
3rdparty/nuxeo/pom.xml

Nuxeo plugin that customizes documents as they are indexed in Elasticsearch. This allows computing synthesized fields and storing them, e.g. for denormalizing fields to enable search across record types.
The initial implementation is hardcoded for the needs of the materials profile/Material Order application. This will be configurable in the future.

DRYD-559: Initial implementation of ES document writer.

---

3rdparty/nuxeo/nuxeo-platform-listener/build.xml
3rdparty/nuxeo/nuxeo-platform-listener/pom.xml
3rdparty/nuxeo/nuxeo-platform-listener/reindex/build.properties
3rdparty/nuxeo/nuxeo-platform-listener/reindex/build.xml
3rdparty/nuxeo/nuxeo-platform-listener/reindex/pom.xml
3rdparty/nuxeo/nuxeo-platform-listener/reindex/src/main/java/org/collectionspace/services/listener/Reindex.java
3rdparty/nuxeo/nuxeo-platform-listener/reindex/src/main/java/org/collectionspace/services/listener/ReindexSupport.java
3rdparty/nuxeo/nuxeo-platform-listener/reindex/src/main/resources/META-INF/MANIFEST.MF
3rdparty/nuxeo/nuxeo-platform-listener/reindex/src/main/resources/OSGI-INF/deployment-fragment.xml
3rdparty/nuxeo/nuxeo-platform-listener/reindex/src/main/resources/OSGI-INF/event-contrib.xml

A Nuxeo event listener to trigger reindexing of records in Elasticsearch when associated records are created/modified/deleted. When a record is created or updated, Nuxeo will automatically reindex it in ElasticSearch, but Nuxeo does not know about other records that may also need to be reindexed; for example, if a related record denormalizes data from the updated record at index time. This listener will ensure that all associated records that also need to be reindexed are reindexed.
This initial implementation will only be a proof-of-concept, hardcoded for the needs of the materials profile/Material Order application. In the future, the listener will be configurable to trigger reindexing of different kinds of records/relations.

DRYD-560: Initial implementation of ES reindexing event listener.

---

services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CSpaceResteasyBootstrap.java
services/config/src/main/resources/service.xsd

Implement a property to reindex all records in Elasticsearch.
This works similarly to reinitializing authorities. If the system property org.collectionspace.services.elasticsearch.reset is set to true, all Elasticsearch-indexed records will be asynchronously re-indexed when the services layer starts.
For a record to be reindexed, the record type must be configured in the tenant bindings with the attribute elasticsearchIndexed="true".

DRYD-561: Implement property to reindex all records in ES.

---

3rdparty/nuxeo/nuxeo-server/7.10-HF17/config/proto-elasticsearch-extension.xml

Update the default Nuxeo Elasticsearch configuration in 3rdparty/nuxeo/nuxeo-server/7.10-HF17/config/proto-elasticsearch-extension.xml.
Add analyzers that are useful for cspace:
- analyzer to extract the display name from a ref name for indexing
- analyzer to extract the short id of a ref name for indexing
- analyzer to remove the tenant qualification from a doctype when indexing
- analyzer to lowercase and ascii-fold a value, for case- and accent-insensitive sorting
Remove mappings for fields that are not used by cspace, like all dc and some ecm fields.

DRYD-562: Update default Elasticsearch configuration.

---

3rdparty/nuxeo/build.xml
3rdparty/nuxeo/nuxeo-server/7.10-HF17/config/proto-datasource-config.xml
build.properties

Adding a build property to override Nuxeo's default JDBC datasource value of "jdbc/default".

Remove data source binding errors in logs on cspace startup.

---

services/batch/service/src/main/java/org/collectionspace/services/batch/AbstractBatchInvocable.java
services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/AbstractBatchJob.java
services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/BatchDocumentModelHandler.java
services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/TestBatchJob.java

See DRYD-878.  This update provides backward compatibility with batch jobs written for <= v6.0.

DRYD-878: Added support for older run method to prevent a required version bump.

---

services/IntegrationTests/src/main/resources/log4j2-surefire.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/authority.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/contactSubresource.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/personitemWithContact1.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/personitemWithContact2.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/res/contactItems.res.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/authority/res/personItemsWithContact.res.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/xml-replay-master.xml
services/authority/service/src/main/java/org/collectionspace/services/common/vocabulary/AuthorityResourceWithContacts.java
services/organization/client/src/test/java/org/collectionspace/services/client/test/OrgAuthorityServiceTest.java
services/person/client/src/test/java/org/collectionspace/services/client/test/PersonAuthorityServiceTest.java
services/pom.xml

DRYD-961 - Added code to prevent more than one contact per authority term.  Also, added new XMLReplay unit tests and adjusted existing Surefire tests.

DRYD-961 - Added code to prevent more than one contact per authority term.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/object_valuation.jrxml

The intent of this report is to be run
- from any list of objects (NOT from a single object record, since that'd always be a 1-row report you can easily get from looking at related valuation controls. NOT from group, since I'm planning an additional "related_objects_valuation" report that produces the same basic output, but the query will take one or more csids of procedures that can be related to objects)
- no-context, in which case it runs over all objects
The report is documented in [the Report Repository](https://collectionspace.atlassian.net/wiki/spaces/COL/pages/2672361473/Report+Details+Object+Valuation+DRAFT+WORK+IN+PROGRESS)
Report record payload (attempt): 
```
<ns2:reports_common>
<notes>Returns latest valuation information for selected objects</notes> …
```

add object_valuation report

---

pom.xml

When using maven 3.8.1+, the build of the services layer fails.
The issue appears to be that as of maven 3.8.1, maven no longer allows http addresses for repositories.

DRYD-1194: Updating main pom to use https (vs http)

---

services/report/3rdparty/jasper-cs-report/src/main/resources/Group_List_Basic.jrxml
services/report/service/src/main/java/org/collectionspace/services/report/nuxeo/DefaultReportScriptlet.java
services/report/service/src/main/java/org/collectionspace/services/report/nuxeo/ReportDocumentModelHandler.java

This adds the ability to automatically format ref names as display names (aka, de-urn) when filling reports. This feature is enabled by specifying the `deurnfields` parameter in the report invocation (or by setting a default value for that parameter in the report itself). The `deurnfields` parameter should contain a comma-delimited list of field names. When filling the report, the CollectionSpace server will examine each of the specified fields. If it contains a URN (ref name), then the display name is extracted from the ref name, and used as the value in the field in the report. Otherwise, the value is left unchanged. The `deurnfields` parameter may be set to "*". In that case, all string fields in the report will undergo the de-urning process.
As an example, the …

DRYD-1200, DRYD-1160: Add ability to automatically de-urn report fields.

---

pom.xml
services/common/src/main/java/org/collectionspace/services/common/ServiceMain.java
services/systeminfo/service/src/main/java/org/collectionspace/services/systeminfo/SystemInfoResource.java

Jira: https://collectionspace.atlassian.net/browse/DRYD-1145
* Add build info to manifest for jar and wars
* Use implementation version when getting systeminfo
* I'm not sure if we should add something different for the build number. I was considering pulling in the git commit hash, but left it hardcoded at the moment.
* I added the build info to both war and jars. I wasn't quite sure how everything is bundled together and how the classpath is impacted, and this seemed like the easiest way to make sure it made it into the systeminfo modules.
* The diff was kind of all over the place with formatting initially so I had intellij reformat SystemInfoResource and made changes on top of that.

DRYD-1145: Get version info from implementation version

---

.gitignore
build.properties
cspace-ui/anthro/build.properties
cspace-ui/bonsai/build.properties
cspace-ui/botgarden/build.properties
cspace-ui/build.xml
cspace-ui/build_js.sh
cspace-ui/fcart/build.properties
cspace-ui/herbarium/build.properties
cspace-ui/lhmc/build.properties
cspace-ui/materials/build.properties
cspace-ui/publicart/build.properties

This adds the ability to optionally locally check out and build UI packages from source, instead of downloading pre-built distributions that were published to npm.
If the environment variable `CSPACE_UI_BUILD` is set to `true`, the cspace-ui package and all enabled tenant plugins are cloned from github and built from source. The branches to build from are specified in build.properties files.
This allows the nightly build to use the latest in-development UI packages, without the need to publish possibly untested work to npm. This makes it easier to evaluate in-progress work, without sharing it with the rest of the world.
If `CSPACE_UI_BUILD` is not set …

Optionally build UI packages from source.

---

services/blob/service/src/main/java/org/collectionspace/services/blob/BlobResource.java
services/media/service/src/main/java/org/collectionspace/services/media/MediaResource.java
services/report/service/pom.xml
services/report/service/src/main/java/org/collectionspace/services/report/jasperreports/CSpaceReportScriptlet.java
services/report/service/src/main/java/org/collectionspace/services/report/jasperreports/CSpaceRepositoryExtensionsRegistryFactory.java
services/report/service/src/main/java/org/collectionspace/services/report/jasperreports/CSpaceRepositoryService.java
services/report/service/src/main/java/org/collectionspace/services/report/nuxeo/ReportDocumentModelHandler.java
services/report/service/src/main/resources/jasperreports_extension.properties

This adds a [JasperReports extension](https://jasperreports.sourceforge.net/api/net/sf/jasperreports/extensions/package-summary.html) that allows reports to include images from media record content. The extension registers a [RepositoryService](https://jasperreports.sourceforge.net/api/net/sf/jasperreports/repo/RepositoryService.html) that handles URLs with the `cspace` protocol.
To display media content, report authors can add images with expressions like `"cspace://media/" + $F{mediacsid} + "/blob/derivatives/Thumbnail/content"`. The reporting engine will retrieve the content for the specified media csid and derivative to display in the report. `Thumbnail` can be replaced with any valid derivative name.
This also moves the CSpace JasperReports scriptlet from #312 …

DRYD-1221: Support media images in reports.

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/chronology/build.xml
services/chronology/client/pom.xml
services/chronology/client/src/main/java/org/collectionspace/services/client/ChronologyAuthorityClient.java
services/chronology/client/src/main/java/org/collectionspace/services/client/ChronologyAuthorityClientUtils.java
services/chronology/client/src/main/java/org/collectionspace/services/client/ChronologyAuthorityProxy.java
services/chronology/client/src/test/java/org/collectionspace/services/client/ChronologyAuthorityServiceTest.java
services/chronology/jaxb/pom.xml
services/chronology/jaxb/src/main/java/org/collectionspace/services/ChronologyJAXBSchema.java
services/chronology/jaxb/src/main/resources/chronology_common.xsd
services/chronology/jaxb/src/main/resources/chronologyauthority_common.xsd
services/chronology/pom.xml
services/chronology/service/pom.xml
services/chronology/service/src/main/java/org/collectionspace/services/chronology/ChronologyAuthorityResource.java
services/chronology/service/src/main/java/org/collectionspace/services/chronology/nuxeo/ChronologyAuthorityConstants.java
services/chronology/service/src/main/java/org/collectionspace/services/chronology/nuxeo/ChronologyAuthorityDocumentModelHandler.java
services/chronology/service/src/main/java/org/collectionspace/services/chronology/nuxeo/ChronologyConstants.java
services/chronology/service/src/main/java/org/collectionspace/services/chronology/nuxeo/ChronologyDocumentModelHandler.java
services/chronology/service/src/main/java/org/collectionspace/services/chronology/nuxeo/ChronologyValidatorHandler.java
services/pom.xml

Creates a new Chronology Authority
https://collectionspace.atlassian.net/browse/DRYD-1133
This new authority allows records to reference eras (e.g. archaeological, geological, historical, etc) and events (e.g. presidential terms, wars, olympic games, etc).
With Application PR:
* Verify that cspace is able to build and deploy;
* Once the server is running check that the authority and vocabularies are able to be queried, e.g.
* curl -u 'admin@core.collectionspace.org:Administrator' http://localhost:8180/cspace-services/chronologyauthorities
* curl -u 'admin@core.collectionspace.org:Administrator' …

DRYD-1133: Chronology Authority

---

services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan_letter.jrxml

https://collectionspace.atlassian.net/browse/DRYD-1176
Report was requested by OHC
1. Register the report with collectionspace, e.g.
```
[incoming-loan] $ cat report.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<document name="report">
 <ns2:reports_common xmlns:ns2="http://collectionspace.org/services/report">
 <name>Incoming Loan Letter</name>
 <notes>loan letter</notes>
 <forDocTypes>
   <forDocType>Loanin</forDocType>
 </forDocTypes>
 <supportsSingleDoc>true</supportsSingleDoc>
 <supportsDocList>false</supportsDocList>
 <supportsGroup>false</supportsGroup>
 <supportsNoContext>true</supportsNoContext> …
```

DRYD-1176: Add incoming loan letter report

---

services/chronology/client/src/main/java/org/collectionspace/services/client/ChronologyAuthorityClientUtils.java
services/chronology/client/src/test/java/org/collectionspace/services/client/test/ChronologyAuthorityServiceTest.java

Fixes failing test for chronology
Update variable name to be chronology in its util class 
The cspace nightly build is failing because of two tests in chronology - `verifyIllegalItemDisplayName` and `testItemSubmitRequest`.
When running the tests, `testItemSubmitRequest` was failing because the url being created was incorrect and need to use the  `AuthorityClient.ITEMS` path. `verifyIllegalItemDisplayName` was giving a NPE which appears to have been resolved though it wasn't addressed directly. I did move the test class into the test package to be consistent with other authorities but nothing else was changed for it. 
* Run `mvn test` and verify …

DRYD-1133: Update chronology tests

---

services/report/3rdparty/jasper-cs-report/src/main/resources/box_list.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/box_list.xml

Adds a `box_list` report
Report originally requested by OHC
https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1178
* Create a LMI with the following:
* Current Location
* Related Object w/ object name + related media  
* Register the report with the server for single docs:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<document name="report">
 <ns2:reports_common xmlns:ns2="http://collectionspace.org/services/report">
 <name>Box List</name>
 <notes>boxlist</notes>
 <forDocTypes>
   <forDocType>Movement</forDocType>
 </forDocTypes>
 <supportsSingleDoc>true</supportsSingleDoc> …
```

DRYD-1178: Create boxlist report

---

3rdparty/nuxeo/nuxeo-platform-elasticsearch/pom.xml
3rdparty/nuxeo/nuxeo-platform-thumbnail/pom.xml
pom.xml
services/JaxRsServiceProvider/pom.xml
services/account/jaxb/pom.xml
services/authentication/jaxb/pom.xml
services/authority/pom.xml
services/authority/service/pom.xml
services/authorization-mgt/jaxb/pom.xml
services/authorization/jaxb/pom.xml
services/common/pom.xml
services/hyperjaxb/pom.xml
services/imports/service/pom.xml
services/pom.xml

This upgrades dom4j to 2.1.4. It's more complicated than it should be, because the group id of dom4j changed from `dom4j` to `org.dom4j` after 1.6. Normally, we could do an upgrade by setting the desired version number of the artifact in a `dependencyManagement` block, which would cause that version to be used by all transitive dependencies. However, since the group id changed, setting the version number of `org.dom4j:dom4j` to 2.1.4 won't affect transitive dependencies on `dom4j:dom4j`, since it's a different group id. So we need to find all our dependencies that have a transitive dependency on `dom4j:dom4j`, and exclude it from those dependencies. Then, in all the modules that use those dependencies, we need to add a dependency on `org.dom4j:dom4j:2.1.4`, to …

Upgrade dom4j to 2.1.4.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan_letter.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan_letter.xml

Adds xml for registering the incoming loan letter report with cspace
Small edit to the incoming loan letter report to only fetch the first term group for person/organizations
To assist with registering reports
Test that the xml can be used in the report API call, e.g.
```
curl -X POST http://localhost:8180/cspace-services/reports -i -u admin@core.collectionspace.org:Administrator -H "Content-Type: application/xml" -T incoming_loan_letter.xml
``` 
n/a
n/a
@mikejritter …

DRYD-1176: Add xml payload for incomingloanletter

---

services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan_letter.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan_letter.xml

Add report for outgoing loan letter
Add xml for registering outgoing loan letter
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1177
Report previously requested by OHC
* Register the report with collectionspace using the provided xml :D 
* Create a LoanOut with...
* A Borrower with...
* An address w/ however many fields filled out
* A Borrower Contact 
* A loan out date
* A loan renewal date
* Run the `Outgoing Loan Letter` Report for the Loan Out procedure
None.
@ray-lee I'm likely going to do some more reading on the `MATERIALZED` vs `NOT MATERIALIZED` options. I haven't had performance …

DRYD-1177: Add outgoing loan letter report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.xml

* Adds report for accessions
* Adds xml for registering accessions report
Jira: https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1129
* Register the report with collectionspace using the provided xml 
* Create an Acquisition with
* Accession date, acquisition date, acquisition method, acquisition source, note, provisos, credit line, and approval group
* Related object with: object name, production date, collection, brief description, history note, related media for thumbnail
* Run the Accession Report for the Acquisition procedure
None
**Has the …

DRYD-1129: Add accessions report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.xml

* Adds deed of gift report
* Adds xml for registering deed of gift report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1118
* Register the deed of gift report
* Create a collection object with
* brief description
* object name
* production date
* related media 
* Create a person authority with
* Additional term group + display name
* Address group filled out
* Create an Intake with
* current owner (person authority)
* related object from above
* Run the report and verify output is as expected
None
**Has the application documentation been updated for these …

DRYD-1118: Deed of Gift report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.xml

* Add deaccession report
* Add xml for registering deaccession report with cspace
Jira: https://collectionspace.atlassian.net/browse/DRYD-1130
* Register the report with collectionspace
* Create an ObjectExit procedure with most (all? ) fields filled out
* Create a CollectionObject with media + relate to the ObjectExit
* Create an Acquisition + relate to the ObjectExit
* Crete an Intake + relate to the ObjectExit
None
No
@mikejritter tested w/ all …

DRYD-1130: Add deaccession report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_budget.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_budget.xml

* Adds report for Tombstone with budget and related media thumbnail
* Adds xml for registering report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1195
This is a report for publicart (I assume requested by them though the jira does not state this)
* Create the report for the publicart tenant w/ the provided xml
* Create a CollectionObject record with the following fields:
* Title, Creator, Brief Description, Collection, Owner, Installation Type, Work Type, Material, Dimension, Artwork Date
* Create a related Acquisition with the follow fields:
* Funding value, funding currency
* Create a related Media with an image for the thumbnail
* From …

DRYD-1195: Tombstone with budget + image report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/obj_current_place_details.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_current_place_details.xml

* Creates report for object w/ current place
Jira: https://collectionspace.atlassian.net/browse/DRYD-1197
Report for publicart
* Register the report with collectionspace using the provided xml
* Create a collectionobject with
* title, description
* Create a place authority with
* type, owner (all), address (all), latitude, longitude, and broader place
* Create a movement with
* current location as the above authority, current location note
* Search for collectionobjects
* Select one or more of the search results and run the report
This is for the publicart profile, so we just need to make sure the …

DRYD-1197: Object with Full Current Place Report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.xml

* Adds report for Object w/ Computed Current Location
* Adds xml for register report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1199
Report originally requested by Public Art
* Register the report with cspace
* Create a collectionobject with
* title, object name, brief description
* Create a location authority with
* term display name and term name
* Create a LMI with the above authority as the current location
* Relate the LMI and collectionobject
* Create a related media for the collectionobject
* Search on collectionobjects and execute the report
The Jira states `Storage Location or …

DRYD-1199: Basic Object with Computed Location Report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/box_list.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/box_list.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan_letter.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan_letter.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_budget.jrxml

This PR updates many of the queries for the new csv reports in order to ignore relations on objects/procedures which have been deleted. 
When testing on dev we saw some reports generating many more rows than expected and when looking into the cause I found that there were deleted relations being retrieved in the report. This work is being done in order to remove those rows from the reports.
I also updated the default output to be `text/csv`.
Most of the reports only query for related objects and media on said objects, what I have is:
* A single base collectionobject and 2 media handling procedures
* Relate the collectionobject with the media
* Delete on …

Update relation queries for reports

---

services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan.xml

* Adds incoming loan report
* Adds xml for registering incoming loan report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1119
* Register the report with CSpace
* Create a Loanin with the following fields:
* Loan status group, loan status date, loan lender, loan lender contact (+address filled out), loan in date, loan renewal application date
* Create a related collectionobject with the following:
* object name
* Create a related valuation control for either the loanin or collectionobject with:
* amount value and currency
* Run the report on the loanin and verify the output is as expected …

DRYD-1119: Incoming loan report

---

services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CSpaceResteasyBootstrap.java
services/batch/service/src/main/java/org/collectionspace/services/batch/BatchResource.java
services/client/src/main/java/org/collectionspace/services/client/IQueryManager.java
services/common/src/main/cspace/config/services/tenants/publicart/publicart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/common/src/main/java/org/collectionspace/services/common/query/QueryManager.java
services/common/src/main/java/org/collectionspace/services/common/query/nuxeo/QueryManagerNuxeoImpl.java
services/jaxb/src/main/java/org/collectionspace/services/jaxb/InvocableJAXBSchema.java
services/report/3rdparty/build.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/Acq_List_Basic.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/CC_List_Basic.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/Exhibition_List_Basic.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/Group_List_Basic.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/LoansIn_List_Basic.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/LoansOut_List_Basic.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/acq_basic.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreAcquisition.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreGroupObject.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreIntake.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanIn.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanOut.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreObjectExit.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/object_valuation.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/systematicInventory.xml
services/report/client/src/main/java/org/collectionspace/services/client/ReportClient.java
services/report/service/src/main/java/org/collectionspace/services/report/ReportResource.java
services/report/service/src/main/java/org/collectionspace/services/report/nuxeo/ReportDocumentModelHandler.java

This automatically adds and updates reports on startup. Reports to add are configured in tenant bindings.
To add reports to all tenants, add the report name (the filename of the report, excluding the `.jrxml` extension) to tenant-bindings-proto-unified.xml. Follow the examples in this PR.
To add reports only to specific tenants, add the report name to the delta file for the tenant, e.g. publicart-tenant-bindings.delta.xml. Follow the examples in this PR.
If a report has already been installed, its metadata is updated from the installed xml file only if: the existing report metadata record was originally automatically created; it has not been updated by another user since it was created; and it has not been soft-deleted. …

DRYD-1230: Automatically add/update reports on startup.

---

services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/condition.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/condition.xml

* Adds condition report
* Adds xml for registering report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1198
Report requested by Public Art
* Register the report w/ collectionspace
* Create a collectionobject with
* title, related location, related media
* Create a related conditioncheck with
* Check/Assessment Date 
* Method
* Note
* Reason
* Assessor
* Object Audit Category
* Conversation Treatment Priority
* Next assessment date
* Condition Check Completeness Description
* Technical Assessment Description
* Condition Check Condition Description
* Condition Check Environmental Condition Note
* Display Recommendation
* Handling Recommendation …

DRYD-1198: Condition report

---

services/common/src/main/cspace/config/services/tenants/publicart/publicart-tenant-bindings.delta.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_creator.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_creator.xml

* Adds tombstone with creator report
* Adds xml for registering report
* Update publicart bindings to register report on startup
* Jira: https://collectionspace.atlassian.net/browse/DRYD-1196
* Report requested by PublicArt
* Deploy the changes to collectionspace
* Using the publicart ui profile
* Create a collectionobject with: title, description, collection, owner, installation type, work type, mateiral, dimension, creator, creator role, and artwork date
* Create a related media procedure for a thumbnail
* Search for collectionobjects and run the report
* Verify the report output is as expected   …

DRYD-1196: Tombstone with creator report

---

services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan.xml

* Adds report for outgoing loans
* Adds xml for registering report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1120
* Register the report with CSpace
* Create a Loanout with the following fields:
* Loan status group, loan status date, loan borrower (+address filled out), loan borrower contact, loan out date, loan renewal application date
* Create a related collectionobject with the following:
* object name
* Create a related valuation control for either the loanout or collectionobject with:
* amount value and currency
* Run the report on the loanout and verify the output is as expected …

DRYD-1120: Outgoing loan report

---

services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CSpaceResteasyBootstrap.java
services/batch/service/src/main/java/org/collectionspace/services/batch/BatchResource.java
services/batch/service/src/main/resources/org/collectionspace/services/batch/nuxeo/MergeAuthorityItemsBatchJob.xml
services/batch/service/src/main/resources/org/collectionspace/services/batch/nuxeo/UpdateInventoryStatusBatchJob.xml
services/batch/service/src/main/resources/org/collectionspace/services/batch/nuxeo/UpdateObjectLocationBatchJob.xml
services/client/src/main/java/org/collectionspace/services/client/IQueryManager.java
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/common/src/main/java/org/collectionspace/services/common/query/QueryManager.java
services/common/src/main/java/org/collectionspace/services/common/query/nuxeo/QueryManagerNuxeoImpl.java
services/jaxb/src/main/java/org/collectionspace/services/jaxb/InvocableJAXBSchema.java

This automatically adds and updates batch jobs on startup. Batch jobs to add are configured in tenant bindings.
To add batch jobs to all tenants, add the batch job name (the fully qualified class name of the Java implementation) to tenant-bindings-proto-unified.xml. Follow the examples in this PR: 
To add batch jobs only to specific tenants, add the batch job name to the delta file for the tenant, e.g. publicart-tenant-bindings.delta.xml. Follow the examples in this PR: 
The batch job metadata is expected to be a Java resource file accessible from the classloader of the batch job class, with the same name as the class, and the extension `.xml`. For example:
If a batch job has already been installed, its metadata is updated from the xml file on startup only if: the …

DRYD-1233: Automatically add/update batch jobs on startup.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/Acq_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/CC_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/Exhibition_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/LoansIn_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/LoansOut_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreAcquisition.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreGroupObject.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreIntake.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanIn.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanOut.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreObjectExit.jrxml

Updates reports which have refnames to use the new deurnfields parameter
Jira: https://collectionspace.atlassian.net/browse/DRYD-1154
Many of the older reports needed to be updated in order to have any refnames de-urned. This is done by using the deurnfields parameter to handle refnames which appear in the details section of the reports.
Testing requires running of each report in order to validate that the fields returned are de-urned. Many reports retrieve a related collectionobject, which should be created.
* Replace the reports with the updated jrxml
* Create a collectionobject with an objectname, production person role, production person, and …

DRYD-1154: De-urn reports

---

services/report/3rdparty/jasper-cs-report/src/main/resources/LoansOut_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreGroupObject.jrxml
services/report/pom.xml
services/report/service/src/main/java/org/collectionspace/services/report/nuxeo/ReportDocumentModelHandler.java

* Updates jasper to 6.11.0
* Updates formatting for LoanOut Basic List
* Updates formatting for Group Object Ethnographic List 
Jira: https://collectionspace.atlassian.net/browse/DRYD-1164, https://collectionspace.atlassian.net/browse/DRYD-1159
Formatting changes were requested in various jira issues in addition to de-urning. As part of this, there's a new attribute for `textField` so that different approaches can be taken depending on the report. Jasper is being updated as well in order to make use of the new attribute. When nuxeo is updated further we'll have an opportunity to bring Jasper fully up to date.
* Rebuild collectionspace 
* Run the Group …

Update jasper and reformat reports

---

services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/box_list.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/condition.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan_letter.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_current_place_details.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan_letter.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/referral.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_budget.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_creator.jrxml

* Set overflow and null rules for results
This issue was brought up in [DRYD-1198](https://collectionspace.atlassian.net/browse/DRYD-1198) as results were being truncated in the csv report for certain fields. I decided to copy some of the older reports which set overflow rules (using `textAdjust`) and apply them to all fields in the result set so that none of them will have truncation applied and will instead "stretch". In addition I updated the reports so that null fields will be blank instead of returning `null`, which had been done in other reports as well.
* For one of the given reports, create a procedure or object that has enough data to cause an …

Set overflow and null rules for results

---

services/batch/service/src/main/java/org/collectionspace/services/batch/BatchResource.java
services/client/src/main/java/org/collectionspace/services/client/IQueryManager.java
services/report/service/src/main/java/org/collectionspace/services/report/ReportResource.java

This adds a `combine` parameter to list requests for report and batch resources. This controls how the filters (`doctype`, `filename`, `classname`, `mode`) are combined. Set to `or` to combine the filters using an OR operation. No value or any other value will combine the filters using and AND operation.
When viewing a Group record, the reports and batch jobs shown in the sidebar should be _either_ registered for doc type `Group`, _or_ for invocation mode `group`. There was previously no way to combine these filters using an OR operator.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1069
With the default reports installed:
- Request …

Add combine param to report and batch searches.

---

services/batch/service/src/main/java/org/collectionspace/services/batch/nuxeo/BatchDocumentModelHandler.java
services/report/service/src/main/java/org/collectionspace/services/report/nuxeo/ReportDocumentModelHandler.java

This allows reports and batch jobs to be invoked with `mode`=`group` and `docType`=`Group`, or `mode`=`group` and no `docType`, regardless of the `forDocTypes` that the report/batch job was registered with. This should be allowed, because `mode`=`group` implies that the context document is a Group. 
This allows authors to add reports/batch jobs that run in group mode, without also needing to specify `forDocType`=`Group`, which is redundant. It can also be confusing for reports that run in both group and list modes. For example, take a report that runs on lists of Objects, or a group (of Objects). For this, specifying `supportsGroup`=`true` and `supportsList`=`true` along with `forDocType`=[`CollectionObject`, `Group`] …

DRYD-1069: Allow docType to be group or null in group mode invocations.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/coreAcquisition.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreGroupObject.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreIntake.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanIn.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanOut.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreObjectExit.jrxml

This removes the "powered by" and CollectionSpace logo image from report footers.
Several reports contributed by UC Berkeley contained this in the footer. The logo was retrieved from the URL https://pahma.cspace.berkeley.edu/collectionspace/ui/pahma/images/header-logo-cspace.png, which was not accessible outside of UC Berkeley, so a broken image icon would appear. This text and logo are removed, to be consistent with other reports.
The following affected reports should continue to run successfully. There should be no "powered by" text, CollectionSpace logo, or image icon in the footer.
- Acquisition Ethnographic Object List
- Group Object Ethnographic …

DRYD-1237: Remove 'powered by' and CSpace logo from report footers.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/referral.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_budget.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_creator.jrxml

This PR updates many of the report queries to perform aggregation on certain fields which exist either in groups or simple lists. Field separators are done with a pipe, and de-urning of fields is done in the query using a regular expression.
Summary of changes are:
* DRYD-1118 (deedofgift): Aggregate termdisplayname
* DRYD-1129 (accessions): Aggregate approvalGroup
* DRYD-1130 (deaccessions): Aggregate deacApprovalGroup; fix typo for deaccession approval note
* DRYD-1132 (referral): Aggregate approvalGroup
* DRYD-1195 (tombstone with budget): Aggregate all fields
* DRYD-1196 (tombstone with creator): Aggregate creator, creator role, material, and objectname
These were requested from feedback as something which is desired …

Aggregation for repeating fields in reports

---

services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_creator.jrxml

Brings in additional changes requested for reports:
* DRYD-1118: Ensure ordering for term names
* DRYD-1130: Add exit quantity
* DRYD-1196: Aggregate dimension values
These changes are the latest requested from testing the reports. For deed of gift, we want to make sure the primary change is first, so we use order by on the aggregation. Deaccession had a typo in the original requested changes which resulted in exit quantity being removed; this has been re-added. In tombstone with creator, the dimension fields were requested to be aggregated. 
* https://collectionspace.atlassian.net/browse/DRYD-1118
* https://collectionspace.atlassian.net/browse/DRYD-1130
* https://collectionspace.atlassian.net/browse/DRYD-1196
**How should …

Additional Report Updates

---

build.properties
services/account/jaxb/src/main/resources/accounts_common.xsd
services/account/jaxb/src/main/resources/accounts_common_list.xsd
services/account/pstore/src/main/resources/db/postgresql/account.sql
services/account/service/src/main/java/org/collectionspace/services/account/AccountResource.java
services/account/service/src/main/java/org/collectionspace/services/account/storage/AccountDocumentHandler.java
services/account/service/src/main/java/org/collectionspace/services/account/storage/AccountValidatorHandler.java
services/authentication/service/pom.xml
services/authentication/service/src/main/java/org/collectionspace/authentication/CSpaceUser.java
services/authentication/service/src/main/java/org/collectionspace/authentication/jackson2/Saml2AuthenticatedCSpaceUserDeserializer.java
services/authentication/service/src/main/java/org/collectionspace/authentication/realm/CSpaceRealm.java
services/authentication/service/src/main/java/org/collectionspace/authentication/realm/db/CSpaceDbRealm.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/CSpaceDaoAuthenticationProvider.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/CSpaceLogoutSuccessHandler.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/CSpaceSaml2Authentication.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/CSpaceSaml2LogoutRequestRepository.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/CSpaceUserDetailsService.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/SSORequiredException.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/Saml2AuthenticatedCSpaceUser.java
services/authorization/service/src/main/java/org/collectionspace/services/authorization/AuthZ.java
services/common/pom.xml
services/common/src/main/cspace/config/services/service-config-security.xml
services/common/src/main/java/org/collectionspace/services/common/authorization_mgt/AuthorizationCommon.java
services/common/src/main/java/org/collectionspace/services/common/security/SecurityConfig.java
services/config/src/main/java/org/collectionspace/services/common/config/ConfigUtils.java
services/config/src/main/resources/service-config.xsd
services/login/service/src/main/java/org/collectionspace/services/login/LoginResource.java

This adds support for single sign on using SAML. 
- SAML identity providers can be configured in XML files.
- Once configured, SAML providers are presented on the log in screen.
- The requireSSO field has been added to accounts. If true, users must use an SSO provider to log in. Attempting to log in using an email/password will fail.
Single sign-on is required by many institutions.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1243
For each SSO provider that has been configured in the services layer, the login screen should present a link to sign in using that provider.
When editing a user (in the Administration tab), the Require single …

DRYD-1243: Add SAML support.

---

services/common/src/main/java/org/collectionspace/services/common/security/SecurityConfig.java
services/config/src/main/java/org/collectionspace/services/common/config/ConfigUtils.java

This fixes a CORS error that happens during SAML logins. During the login process, the SAML identity provider needs to POST to a CSpace services endpoint. In order to allow this POST, the CORS configuration for that endpoint needs to have the SAML IdP added to its allowed origins.
This is part of the SAML implementation work.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1243
Login using SAML on the dev server should work, without any CORS errors.
None.
n/a …

Add SAML providers to CORS allowed hosts.

---

services/common/src/main/java/org/collectionspace/services/common/security/SecurityConfig.java
services/config/src/main/java/org/collectionspace/services/common/config/ConfigUtils.java

This fixes a CORS error that happens during SAML logouts. During the logout process, the SAML identity provider needs to POST to a CSpace services endpoint. In order to allow this POST, the CORS configuration for that endpoint needs to have the SAML IdP added to its allowed origins.
This is similar to #367, but for logout instead of login.
This is part of the SAML implementation work.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1243
When SAML single logout is enabled, logout from a SAML account on the dev server should work, without any CORS errors.
None
**Has the application …

Add SAML providers to CORS allowed hosts for logout.

---

services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/publicart/publicart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/artwork_description.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/artwork_description.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/borrowing_receipt.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/borrowing_receipt.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/box_list.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/full_obj_place.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/full_obj_place.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_current_place_details.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/referral.jrxml

This brings in new reports as well as fixes to reports from 7.2:
* Add Borrowing Receipt report to core
* Add Artwork Description report to fcart
* Add Full Object With Place Details report to publicart
* Add PlaceType field to Object with Full Current Place
* Remove condition on primary type for relation joins
* Deurn objectname field
**New Reports**
Jira: https://collectionspace.atlassian.net/browse/DRYD-1278
These are the 3 new reports which were requested. Fairly straightforward additions. 
**Report Updates**
Jira: https://collectionspace.atlassian.net/browse/DRYD-1282
The updates are from things we saw after 7.2 release which weren't caught by QA. Notably, the `placeType` field was missing from the object w/ current …

Workflow Reports and Report Updates

---

3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/java/org/collectionspace/services/nuxeo/elasticsearch/DefaultESDocumentWriter.java

* Add objectNameControlled to denorm'd title
Jira: https://collectionspace.atlassian.net/browse/CB-20
The controlled version of the object name was added in 7.2, but the elasticsearch index wasn't updated to include it in the title. This updates it so that the controlled object name is second in precedence behind the title.
* Deploy the changes and run collectionspace
* Create three collection objects (published to the publicbrowser):
* One with a title, controlled object name, and object name
* One with a controlled object name and object name
* One with an object name
* Query the elasticsearch index and check that the `collectionspace_denorm:title` is …

CB-20: Use controlled object name in computed title

---

services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml

This indexes the display name of the objectProductionPlace field in the anthro profile, so that the display name can be used as a facet in the public browser, instead of the full ref name.
In the anthro profile, objectProductionPlace is customized to be an authority-controlled field, instead of free text. This was causing ref names to appear as facets in the public browser.
JIRA: https://collectionspace.atlassian.net/browse/CB-22
In the public browser, with https://github.com/collectionspace/cspace-public-browser.js/pull/24 applied, the values in the Production Place facet should no longer appear as ref names (URNs). …

CB-22: Index display name of objectProductionPlace in anthro.

---

3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/java/org/collectionspace/services/nuxeo/elasticsearch/DefaultESDocumentWriter.java
services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml

* Adds a denormalized materialGroupList to capture controlled materials
* Remove old materialGroupList index
Jira: https://collectionspace.atlassian.net/browse/CB-21
This updates the elasticsearch index to capture the controlled version of a material if present. The field was added in 7.2, so this allows the public browser to be up to date with the latest fields.
- Deploy the changes and run collectionspace
- Create a few collection objects (published to the publicbrowser):
- One with a controlled material and material
- One with an uncontrolled material
- Query the elasticsearch index and check that the collectionspace_denorm:materilGropuList is …

CB-21: Include controlled terms for material display

---

3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/java/org/collectionspace/services/nuxeo/elasticsearch/DefaultESDocumentWriter.java
services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml

Adds denormalized objectNameList to elasticsearch for capturing controlled and uncontrolled terms
Jira: https://collectionspace.atlassian.net/browse/CB-23
We added controlled terms for object names but never updating to have them indexed in elasticsearch. This updates it so that both fields are captured 
* Rebuild collectionspace and enable elasticsearch
* Create a collectionobject with multiple controlled and uncontrolled objectnames
* Query elasticsearch and see all the terms returned, e.g.
```
[elastic] $ cat msearch
{"preference":"result"}
{"query":{"term":{"ecm:primaryType":"CollectionObject"}},"from":0,"size":33,"_source":{"includes":["ecm:name","e …
```

CB-23: Add denormalized objectName to capture controlled terms

---

services/common/src/main/cspace/config/services/tenants/bonsai/bonsai-tenant-bindings.delta.xml

This indexes the display name of the objectProductionPlace field in the bonsai profile, so that the display name can be used as a facet in the public browser, instead of the full ref name.
In the bonsai profile, objectProductionPlace is customized to be an authority-controlled field, instead of free text. This was causing ref names to appear as facets in the public browser.
JIRA: https://collectionspace.atlassian.net/browse/CB-22
In the public browser, with https://github.com/collectionspace/cspace-public-browser.js/pull/27 applied, the values in the Production Place facet should no longer appear as ref names (URNs). …

CB-22: Index display name of objectProductionPlace in bonsai.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_budget.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_creator.jrxml

* Use distinct in order to get media for all csids
Jira: https://collectionspace.atlassian.net/browse/DRYD-1328
This was a bug identified when selecting multiple collection objects from the tombstone with budget and tombstone with creator reports. It is caused by the subquery returning a single row instead of one row per object because of using `LIMIT`. To fix this I updated the query to use `DISTINCT` on each csid.
* Rebuild collectionspace with the publicart tenant enabled
* Start collectionspace and run the publicart ui
* Create multiple collectionobjects with associated media
* Search for collectionobjects
* Using a selection of them, run the …

DRYD-1328: Use distinct in order to get media for all rows

---

services/structureddate/structureddate/src/main/antlr4/org/collectionspace/services/structureddate/antlr/StructuredDate.g4
services/structureddate/structureddate/src/main/java/org/collectionspace/services/structureddate/antlr/ANTLRStructuredDateEvaluator.java
services/structureddate/structureddate/src/test/java/org/collectionspace/services/structureddate/StructuredDateEvaluatorTest.java
services/structureddate/structureddate/src/test/resources/test-dates.yaml

* Updates to exitRomanStringDate
* Add additional test dates
* Remove duplicate condition
Jira: https://collectionspace.atlassian.net/browse/DRYD-1249
This is part of the UCB contributions and brings in changes to structured date from their branch. It makes changes to `romanDate` which is now mapped to `romanStringDate`. There was also a duplicate condition which I removed.
I'm not too familiar with structured dates and what's expected of them so I only did some basic testing:
* Build collectionspace
* Run integration tests
* Create a structured date
* This should probably be done with a roman formatted date as well
**Dependencies for merging? Releasing …

DRYD-1249: UCB Structured Date Contrib

---

services/structureddate/structureddate/src/main/java/org/collectionspace/services/structureddate/DateUtils.java

Jira: https://collectionspace.atlassian.net/browse/DRYD-1127
* Include timestamp when formatting structured date scalar values
This is a breaking change, so this will be for 8.x. I'm keeping this a draft until that's ready.

DRYD-1127: Use timestamp formatter for scalar values

---

services/common/src/main/java/org/collectionspace/services/common/vocabulary/RefNameServiceUtils.java
services/jaxb/src/main/resources/authorityrefdocs.xsd

This adds a `value` element to authority ref doc list items, which are returned in the `refobjs` API call, used to find references to a given authority item. The `value` element contains the value of the field that references the authority item.
An authority item may contain multiple synonymous terms, and any of the terms may have been used in other records (assuming the system is configured to allow usage of non-preferred terms). This makes it possible to tell exactly which term has been used to reference an authority item. (The `value` will contain a ref name, whose display name part will indicate the term that was used).
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1327
**How should this be tested? Do these …

DRYD-1327: Add value element to authority ref doc list items.

---

services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/condition.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.jrxml

This updates the joins for `related_media` queries in reports to restrict to a single row of the most recently updated media.
Jira: https://collectionspace.atlassian.net/jira/software/c/projects/DRYD/issues/DRYD-1370
It was determined that returning all related media was not desirable, and that a single thumbnail/csid was preferred. 
* Rebuild collectionspace
* Create 2 Media Handling for testing
* Create a CollectionObject with relations to both Media Handling procedures
* **Basic Object with Current Location**
* Search on CollectionObjects and run `Basic Object with Current Location` report
* Verify the thumbnails are correct for each CollectionObject …

DRYD-1370: Join on most recent media

---

services/common/src/main/java/org/collectionspace/services/common/query/nuxeo/QueryManagerNuxeoImpl.java

This simplifies the preprocessing of keyword search terms that cspace performs before passing the terms on to the Nuxeo search API.
The preprocessing performed is now:
1. Replace all punctuation except for `"` and `*` with space
1. Replace `not {term}` with `-{term}`
This results in the following functional changes:
- `'` can no longer be used to enclose a phrase search (but `"` still can).
- `-` can no longer be used to negate a search term (but `not` still can).
- `%` can no longer be used for a prefix search (but `*` still can).
- `\` can no longer be used to escape (the remaining `*` and `"`) operators (but there was no practical use for this anyway, since punctuation was never indexed).
This makes keyword searches on …

DRYD-1315: Simplify keyword search preprocessing.

---

services/IntegrationTests/src/test/resources/test-data/xmlreplay/collectionobject/repfield_whitesp1.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/collectionobject/repfield_whitesp2.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/collectionobject/repfield_whitesp3.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/collectionobject/repfield_whitesp4.xml
services/IntegrationTests/src/test/resources/test-data/xmlreplay/collectionobject/testCambridge.xml
services/collectionobject/client/src/test/java/org/collectionspace/services/client/test/CollectionObjectServiceTest.java
services/collectionobject/client/src/test/resources/test-data/repfield_whitesp1.xml
services/collectionobject/client/src/test/resources/test-data/repfield_whitesp2.xml
services/collectionobject/client/src/test/resources/test-data/repfield_whitesp3.xml
services/collectionobject/client/src/test/resources/test-data/repfield_whitesp4.xml
services/collectionobject/client/src/test/resources/test-data/testCambridge.xml
services/collectionobject/jaxb/src/main/resources/collectionobjects_common.xsd
services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/bonsai/bonsai-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/materials/materials-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml
services/imports/service/src/test/resources/requests/collectionobject-request.xml

* Add objectCountGroupList to the collectionobject jaxb schema
* Add objectCountGroupList to es included fields
* Add objectCountGroupList to xml templates for testing
* Whitespace cleanup in CollectionObjectServiceTest
Jira: https://collectionspace.atlassian.net/browse/DRYD-1378
This adds objectCountGroupList and related fields where `numberOfObjects` is used in the services layer. It does not remove numberOfObjects but lets them live side by side until the migration is complete.
* Rebuild collectionspace
* Run the integration tests
Some of the xml files do not appear to be used, so some of this is …

DRYD-1378: Updates for objectCountGroup

---

services/report/3rdparty/jasper-cs-report/src/main/resources/Acq_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/CC_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/Exhibition_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/Group_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/LoansIn_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/LoansOut_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/catalogue_sheet.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/full_obj_place.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/systematicInventory.jrxml

This removes the usage of `numberofobjects` in reports and performs a join on the new `objectcountgroup` table in order to use `objectcount`.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1373
As part of replacing the `numberofobjects` field, we need to update references to it in various places. This step is for updating the reports which rely on that field so that they can continue to be used with the correct information.
* Deploy collectionspace
* Create a CollectionObject with one or more `objectCount`s.
* Run the following reports:
* Acquisition, Acquisition Basic List - requires a related collectionobject
* Condition Check, ConditionCheck …

DRYD-1373: Update reports that use numberofobjects

---

services/structureddate/structureddate/pom.xml
services/structureddate/structureddate/src/main/java/org/collectionspace/services/structureddate/DateUtils.java

This fixes failures to parse certain date formats on February 29. When constructing Joda DateTime and MutableDateTime objects, the object is now initialized to the instant 0 (1970-01-01T00:00:00Z). Since the day-of-month is now initialized to 1, this avoids having an intermediate state in which the year gets updated via setter to a non-leap year, but the month and day-of-month are 2 and 29, which was causing an invalid date exception.
This also updates the joda-time library to the latest version, which isn't necessary for the fix.
Structured date parser tests failed on 2/29/2024. JIRA: https://collectionspace.atlassian.net/browse/DRYD-1396
This is …

DRYD-1396: Fix structured date parser failures on February 29.

---

3rdparty/nuxeo/nuxeo-platform-elasticsearch/src/main/java/org/collectionspace/services/nuxeo/elasticsearch/DefaultESDocumentWriter.java
services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/bonsai/bonsai-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml

* Creates aggregate field for indexing content fields
Jira: https://collectionspace.atlassian.net/jira/software/c/projects/CB/issues/CB-26
This work is to help simplify the public browser logic for displaying these related fields under a single heading. It also resolves the issue of indexed items being in the detail display for an object but not being seen in the filter panel.
* Rebuild collectionspace with elasticsearch enabled
* Create a collectionobject with the content concept, organization, event, persons, and description filled out
* Query elasticsearch for the denormalized field, e.g.
```
[publicbrowser] $ cat subject.json …
```

CB-26: Add denormalized field for content fields

---

services/report/3rdparty/jasper-cs-report/src/main/resources/artwork_description.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/artwork_description.xml

This makes numerous changes to the artwork description report from QA.
* Allows the report to be run from the object search result page
* Aggregates all repeating values, delimited by semi-colons
* Updates aggregation for dimensions to separate by measured part
* Gets distinct thumbnails, ordered by the most recently updated
Jira: https://collectionspace.atlassian.net/browse/DRYD-1280
These are changes requested from QA feedback. In addition while doing testing of my own I noticed that the dimension aggregation was often confusing if multiple measured parts/dimensions were being used. Likewise I added in the distinct query for media which was requested for some other reports, and seemed to make sense here in order for a …

Artwork Description Report Updates

---

services/report/3rdparty/jasper-cs-report/src/main/resources/tombstone_with_creator.jrxml

This adds the production date type to the artwork date field
Jira: https://collectionspace.atlassian.net/browse/DRYD-1196
This change was requested for the public art profile to modify the response for the artwork date field. It brings in the production date type which is the adjacent field in the group.
* Using the publicart profile
* Create a collectionobject with
* Artwork date and type (Production Information)
* Search for objects and run the Tombstone with Creator Report
None
No
**Did someone actually run this code to verify …

Update Tombstone with Creator Report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/borrowing_receipt.jrxml

This makes updates to the borrowing receipt from qa feedback.
* Get the most recent thumbnail for objects
* Aggregate data for all repeatable fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1279
By having only the most recent thumbnail display, we avoid returning multiple rows for each object for each thumbnail. This is especially good for csvs where nothing is shown, and data ends up looking redundant.
The aggregation of data was requested for fields which are repeatable. This report will only aggregate per object, so multiple rows can still be returned. This seemed like the best way to handle displaying the data since it can only be run on a single loan out record.
**How should this be tested? Do these …

Borrowing Receipt Report Updates

---

services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.jrxml

* Adds acquisitionmethod to deurn fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1129
When running this report in the publicart profile it was seen that acquisitionmethod was returning the cspace urn. This updates the report so that the acquisitionmethod field is included with the deurnfields so that it uses its display name. 
* Run the acquisitions report on the publicart profile
* See that the acquisitionmethod field is deurn'd
No
None
@mikejritter tested

Deurn acquisitionmethod in accessions report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/full_obj_place.jrxml

This adds the place note to the full object with place report
Jira: https://collectionspace.atlassian.net/browse/DRYD-1281
After testing in QA it was requested to add place note as a field to this report.
* Run the publicart ui devserver
* Create a collectionobject with a related place (from the currentcomputedlocation)
* Run the full object with place report
* Verify that the place note exists for the report
None
No
@mikejritter tested

Add placenote to full object with place report

---

services/common/src/main/cspace/config/services/tenants/lhmc/lhmc-tenant-bindings.delta.xml

* Add the elasticsearch config to the tenant bindings for lhmc
* Add displayName index for production place
Jira: https://collectionspace.atlassian.net/jira/software/c/projects/CB/issues/CB-29
For LHMC the objectProductionPlace field uses the place authority and needs to be deurned when being indexed for the public browser. This handles the services side of this change and adds the config/updates the objectProductionPlace field.
* Build collectionspace with the lhmc tenant enabled
* Deploy the gateway with settings for lhmc
```
zuul:
routes:
lhmc-cspace-services:
path: /lhmc/cspace-services/**
url: http://localhost:8180/cspace-services
username: …
```

LHMC ElasticSearch Config

---

src/main/resources/db/postgresql/upgrade/8.0.0/post-init/01_collectionobject.sql

Create a script for migrating collectionobjects_common.fieldCollectionPlace into collectionobjects_common_fieldcollectionplaces. This allows for the field to be repeatable.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1395
The fieldCollectionPlace field was requested to be updated to be a repeating field. Any data from 7.2 needs to be migrated and inserted it into the new table collectionobjects_common_fieldcollectionplaces. 
* Using collectionspace 7.2, create a collectionobject with a fieldCollectionPlace
* As a side note - I had to update cspace.meta because I built with 8.0.0-SNAPSHOT 
* Stop collectionspace
* Using this PR, rebuild …

Add migration script for collectionobject fieldCollectionPlaces

---

services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml

Moves the report service binding before the elastic index configuration
Jira: https://collectionspace.atlassian.net/jira/software/c/projects/CB/issues/CB-31
When testing the public browser against fcart we saw that `objectProductionPlace` wasn't being de-urned correctly. This was strange because it had been working prior to 8.0,  and other profiles were indexing refnames correctly.
Upon investigation I found that the fcart index was using the default es config from the tenant-bindings-proto-unified.xml. Looking at the merged fcart tenant bindings I noticed that there were two entries for the `tenant:elasticSearchIndexConfig`. Adjusting the declared bindings in the fcart-tenant-bindings.delta.xml so that they matched the …

Adjust bindings so that replacement happens in the correct order

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/dutyofcare/build.xml
services/dutyofcare/client/pom.xml
services/dutyofcare/client/src/main/java/org/collectionspace/services/client/DutyofcareClient.java
services/dutyofcare/client/src/main/java/org/collectionspace/services/client/DutyofcareProxy.java
services/dutyofcare/client/src/test/java/org/collectionspace/services/client/DutyofcareServiceTest.java
services/dutyofcare/jaxb/pom.xml
services/dutyofcare/jaxb/src/main/java/org/collectionspace/services/DutyofcareJAXBSchema.java
services/dutyofcare/jaxb/src/main/java/org/collectionspace/services/DutyofcareListItemJAXBSchema.java
services/dutyofcare/jaxb/src/main/resources/dutyofcares_common.xsd
services/dutyofcare/pom.xml
services/dutyofcare/service/pom.xml
services/dutyofcare/service/src/main/java/org/collectionspace/services/dutyofcare/DutyofcareResource.java
services/dutyofcare/service/src/main/java/org/collectionspace/services/dutyofcare/nuxeo/DutyofcareConstants.java
services/dutyofcare/service/src/main/java/org/collectionspace/services/dutyofcare/nuxeo/DutyofcareDocumentModelHandler.java
services/dutyofcare/service/src/main/java/org/collectionspace/services/dutyofcare/nuxeo/DutyofcareValidatorHandler.java
services/pom.xml

* Creates the DutyOfCare procedure
Jira: https://collectionspace.atlassian.net/browse/DRYD-1332
This is one of the procedures for the NAGPRA support we're working on for the next release.
* Rebuild collectionspace
* Run the test suite against collectionspace
Not a dependency but I've been playing around with using spotless to handle formatting. I added it to the parent dutyofcare pom, and it can be run with `mvn spotless:check` or `mvn spotless:apply`. I'm only doing it for the procedures for now as applying to everything is slightly overwhelming.
**Has the application documentation been updated for …

Add DutyOfCare

---

services/authentication/pstore/src/main/resources/db/postgresql/authentication.sql

This fixes a bug in upgrading older users tables to 8.0. Due to the Spring Security upgrade, the salt in 8.0 is incorporated into the password (`passwd`) column, instead of being a separate column. When upgrading, rows with null salt were treated as if they had an empty ("") salt, resulting in an incorrect `passwd`.
This caused older users (pre-5.0) to not be able to log in after upgrading to 8.0.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1412
- Set some rows in the `users` table to resemble a pre-8.0 table:
- The `passwd` column should contain only a hashed password (no prefixes contained in curly braces)
- The `salt` column should have …

DRYD-1412: Fix handling of null salt when upgrading users table.

---

build.properties
services/account/service/src/main/java/org/collectionspace/services/account/AccountResource.java

This sets the login link on the password reset page to be tenant-specific UI authorization page.
Previously, the login link on the password reset page went to the services login page (/cspace-services/login) instead of the UI page that initiates authorization. This caused the error described in DRYD-1417.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1417
See also https://github.com/collectionspace/cspace-ui.js/pull/213.
See the reproduction steps in the above JIRA.
This works in tandem with https://github.com/collectionspace/cspace-ui.js/pull/213 to fix DRYD-1417, but doesn't break …

DRYD-1417: Set password success login URL to UI authorization page.

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/nagpra-jaxb/pom.xml
services/nagpra-jaxb/src/main/resources/nagpra_common.xsd
services/pom.xml
services/summarydocumentation/build.xml
services/summarydocumentation/client/pom.xml
services/summarydocumentation/client/src/main/java/org/collectionspace/services/client/SummaryDocumentationClient.java
services/summarydocumentation/client/src/main/java/org/collectionspace/services/client/SummaryDocumentationProxy.java
services/summarydocumentation/client/src/test/java/org/collectionspace/services/client/test/SummaryDocumentationServiceTest.java
services/summarydocumentation/jaxb/pom.xml
services/summarydocumentation/jaxb/src/main/java/org/collectionspace/services/SummaryDocumentationJAXBSchema.java
services/summarydocumentation/jaxb/src/main/java/org/collectionspace/services/SummaryDocumentationListItemJAXBSchema.java
services/summarydocumentation/jaxb/src/main/resources/summarydocumentations_common.xsd
services/summarydocumentation/pom.xml
services/summarydocumentation/service/pom.xml
services/summarydocumentation/service/src/main/java/org/collectionspace/services/summarydocumentation/SummaryDocumentationResource.java
services/summarydocumentation/service/src/main/java/org/collectionspace/services/summarydocumentation/nuxeo/SummaryDocumentationConstants.java
services/summarydocumentation/service/src/main/java/org/collectionspace/services/summarydocumentation/nuxeo/SummaryDocumentationDocumentModelHandler.java
services/summarydocumentation/service/src/main/java/org/collectionspace/services/summarydocumentation/nuxeo/SummaryDocumentationValidatorHandler.java

* Create summary documentation service
* Add id generator for summary documentation
* Create nagpra-jaxb module to hold common xsd elements
Jira: https://collectionspace.atlassian.net/browse/DRYD-1333
This adds the summary documentation procedure which is a necessary part of nagpra workflows.
* Rebuild collectionspace and run the integration tests
* Ideally we should also be checking that once deployed the summary documentation api responds correctly, e.g.
* `curl http://localhost:8180/cspace-services/summarydocumentations`
* also PUT with a payload to test the api, though the ui will take care of that as well
**Dependencies for merging? Releasing to …

DRYD-1333: Summary Documentation

---

services/heldintrust/jaxb/src/main/resources/heldintrusts_common.xsd
services/id/service/src/main/java/org/collectionspace/services/id/IDServiceJdbcImpl.java

* Updates use of Statements to be PreparedStatements
* Wraps autocloseable classes in try-with-resources
* Adds cultural care fields to Held-in-Trust xsd
Jira (for Held-in-Trust): https://collectionspace.atlassian.net/browse/DRYD-1358
I had been playing around with some static analyses tools and they noted the use of Statements in the IDService. Since these queries are accessible through the API it seemed like a good time to go ahead and update them to be PreparedStatements instead, even if it just uses the path parameter for the csid value. I also opted to switch to try-with-resources as a way to handle closing of Connections/PreparedStatements/ResultSets to reduce some of the noise in the finally blocks.
**How should …

Convert Statements to PreparedStatements

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/consultation/build.xml
services/consultation/client/pom.xml
services/consultation/client/src/main/java/org/collectionspace/services/client/ConsultationClient.java
services/consultation/client/src/main/java/org/collectionspace/services/client/ConsultationProxy.java
services/consultation/jaxb/pom.xml
services/consultation/jaxb/src/main/resources/consultations_common.xsd
services/consultation/pom.xml
services/consultation/service/pom.xml
services/consultation/service/src/main/java/org/collectionspace/services/consultation/ConsultationResource.java
services/consultation/service/src/main/java/org/collectionspace/services/consultation/nuxeo/ConsultationDocumentModelHandler.java
services/consultation/service/src/main/java/org/collectionspace/services/consultation/nuxeo/ConsultationValidatorHandler.java
services/pom.xml

* Adds new service for Consultation
* Adds id generator for Consultation
Jira: https://collectionspace.atlassian.net/browse/DRYD-1390
The consultation procedure is part of the 8.1 updates for improving NAGPRA workflows. It adds the ability to document the consultation process itself. 
* Rebuild collectionspace with the related application PR and tenants required for running integration tests
* Start collectionspace
* Run the integration tests
None
No
@mikejritter ran the …

DRYD-1390: Consultation Procedure

---

services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan.jrxml

* Add loan purpose, loan condition, and brief description to outgoing loan report
* Add loan purpose, loan condition, and brief description to incoming loan report
* Add person primary term flag to deed of gift
* Add headers for better formatting for xlsx output
Jira: https://collectionspace.atlassian.net/browse/DRYD-1438
For outgoing loan, incoming loan, and deed of gift, additional fields were requested to be added from users. We're starting to add headers for better formatting of xlsx output as well as we've found out people are using the spreadsheets in order to capture the thumbnails from generated reports. Currently the headers are only in the deed of gift (initial testing) and basic object with current location …

DRYD-1438: Workflow Report Updates

---

3rdparty/nuxeo/nuxeo-server/9.10-HF30/config/proto-repo-config.xml
3rdparty/nuxeo/nuxeo-server/9.10-HF30/config/vcsconfig.sql.txt

This updates the nuxeo full text search configuration to schema-qualify the analyzer (`public.cspace_english` instead of `cspace_english`).
This fixes an error where the `cspace_english` text search configuration could not be found during a postgres auto analyze activity. When autovacuuming, recent versions of postgres use a schema search path containing only `pg_catalog`, so anything in the `public` schema needs to be explicitly schema-qualified.
JIRA: https://collectionspace.atlassian.net/browse/DRYD-1487
Run cspace. Keep an eye on the postgres log. Entries that look like the following should not appear:
```
2024-07-24 17:33:46 UTC::@:[15731]:CONTEXT: …
```

DRYD-1487: Fix text search configuration does not exist error

---

services/dutyofcare/client/src/main/java/org/collectionspace/services/client/DutyofcareClient.java
services/dutyofcare/client/src/test/java/org/collectionspace/services/client/DutyofcareServiceTest.java
services/dutyofcare/jaxb/src/main/resources/dutiesofcare_common.xsd
services/dutyofcare/service/src/main/java/org/collectionspace/services/dutyofcare/DutyofcareResource.java
services/dutyofcare/service/src/main/java/org/collectionspace/services/dutyofcare/nuxeo/DutyofcareDocumentModelHandler.java
services/dutyofcare/service/src/main/java/org/collectionspace/services/dutyofcare/nuxeo/DutyofcareValidatorHandler.java

* Fix pluralization for duty of care
* Change title to dutyOfCareTitle
* Implement validation handler
Jira: https://collectionspace.atlassian.net/browse/DRYD-1332
These changes come from the testing done against Duty of Care. The pluralization update which was requested is being applied here for consistency throughout the procedure. I also noticed that the `title` field exists in the dublin core schema, which was sometimes being pulled back in the search results, so I've updated the field definition to be `dutyOfCareTitle` to avoid that collision.
* Rebuild and start collectionspace
* Test that the Duty of Care service is accessible on the new uri
``` …
```

Duty of Care Updates

---

build.properties
cspace-ui/anthro/WEB-INF/web.xml
cspace-ui/anthro/build.properties
cspace-ui/anthro/public/index.jsp
cspace-ui/bonsai/WEB-INF/web.xml
cspace-ui/bonsai/build.properties
cspace-ui/bonsai/public/index.jsp
cspace-ui/botgarden/WEB-INF/web.xml
cspace-ui/botgarden/build.properties
cspace-ui/botgarden/public/index.jsp
cspace-ui/build.xml
cspace-ui/build_js.sh
cspace-ui/core/WEB-INF/web.xml
cspace-ui/core/build.properties
cspace-ui/core/public/index.jsp
cspace-ui/fcart/WEB-INF/web.xml
cspace-ui/fcart/build.properties
cspace-ui/fcart/public/index.jsp
cspace-ui/herbarium/WEB-INF/web.xml
cspace-ui/herbarium/build.properties
cspace-ui/herbarium/public/index.jsp
cspace-ui/lhmc/WEB-INF/web.xml
cspace-ui/lhmc/build.properties
cspace-ui/lhmc/public/index.jsp
cspace-ui/materials/WEB-INF/web.xml
cspace-ui/materials/build.properties
cspace-ui/materials/public/index.jsp
cspace-ui/publicart/WEB-INF/web.xml
cspace-ui/publicart/build.properties
cspace-ui/publicart/public/index.jsp

This adds deployment scripts to deploy the public browser front-end alongside the staff UI for each tenant. Like the staff UI, the public browser front-end can optionally be built from source, rather than pulling a pre-built release from npm. This is controlled by setting the environment variable `CSPACE_UI_BUILD` to `true`.
Once deployed via `ant deploy`, public browsers are available at `/cspace/{tenant short name}/public`. By default, the gateway is expected to be located at the same scheme, host, and port as the public browser front end, at the path `/gateway/{tenant short name}`. If a different gateway URL is required, it can be set by modifying the ant property `tenant.public.browser.gateway.url` in the file `cspace-ui/{tenant short name}/build.properties`. …

DRYD-1516: Install public browser front-end along with UI.

---

services/JaxRsServiceProvider/pom.xml
services/JaxRsServiceProvider/src/main/java/org/collectionspace/services/jaxrs/CollectionSpaceJaxRsApplication.java
services/build.xml
services/common/src/main/resources/db/postgresql/load_id_generators.sql
services/deaccession/build.xml
services/deaccession/client/pom.xml
services/deaccession/client/src/main/java/org/collectionspace/services/client/DeaccessionClient.java
services/deaccession/client/src/main/java/org/collectionspace/services/client/DeaccessionProxy.java
services/deaccession/client/src/test/java/org/collectionspace/services/client/DeaccessionServiceTest.java
services/deaccession/jaxb/pom.xml
services/deaccession/jaxb/src/main/resources/deaccessions_common.xsd
services/deaccession/pom.xml
services/deaccession/service/pom.xml
services/deaccession/service/src/main/java/org/collectionspace/services/deaccession/DeaccessionResource.java
services/deaccession/service/src/main/java/org/collectionspace/services/deaccession/nuxeo/DeaccessionDocumentModelHandler.java
services/deaccession/service/src/main/java/org/collectionspace/services/deaccession/nuxeo/DeaccessionValidatorHandler.java
services/pom.xml

* Creates a deaccession service
* Creates a deaccession id_generator
Jira: https://collectionspace.atlassian.net/browse/DRYD-1355
The Deaccession procedure adds the ability to capture the decision making around removing an accessioned object. Previously this was part of the ObjectExit procedure, and this is breaking it out into it's own data structure.
* Rebuild and start collectionspace with all tenants required for integration tests
* Run the integration tests and ensure they pass
None
No
**Did someone actually run this code to …

DRYD-1355: Deaccession Service

---

services/JaxRsServiceProvider/src/main/resources/log4j2.xml
services/authentication/pstore/src/main/resources/db/postgresql/authentication.sql
services/authentication/service/src/main/java/org/collectionspace/authentication/CSpaceAuthenticationSuccessEvent.java
services/authentication/service/src/main/java/org/collectionspace/authentication/CSpaceUser.java
services/authentication/service/src/main/java/org/collectionspace/authentication/jackson2/CSpaceUserDeserializer.java
services/authentication/service/src/main/java/org/collectionspace/authentication/jackson2/Saml2AuthenticatedCSpaceUserDeserializer.java
services/authentication/service/src/main/java/org/collectionspace/authentication/realm/CSpaceRealm.java
services/authentication/service/src/main/java/org/collectionspace/authentication/realm/db/CSpaceDbRealm.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/CSpaceUserDetailsService.java
services/authentication/service/src/main/java/org/collectionspace/authentication/spring/Saml2AuthenticatedCSpaceUser.java
services/authorization/service/src/main/java/org/collectionspace/services/authorization/AuthZ.java
services/common/src/main/java/org/collectionspace/services/common/security/CSpaceSaml2ResponseAuthenticationConverter.java
services/common/src/main/java/org/collectionspace/services/common/security/SecurityConfig.java
services/common/src/main/java/org/collectionspace/services/common/security/SecurityUtils.java
services/config/src/main/resources/service-config.xsd

This implements an SSO ID field on CSpace user accounts, which is saved following a successful SAML login, and thereafter used to associate the CSpace user with future SAML logins.
- Add `sso_id` column to `users` table, and `ssoId` property to `CSpaceUser`
- Allow configuration of a location (either attribute or NameID) to find the user's IdP-specified ID in a SAML assertion
- Upon successful SAML login:
- Look for a CSpace user whose SSO ID is the IdP-specified ID from the assertion
- If found:
Log in as that CSpace user 
- If not found:
Look for a CSpace user whose username is the email address from the assertion
- If found: Check if the CSpace user has a non-null SSO ID
- If so: Fail the login, since this is unexpected
- If not: Save the  IdP-specified ID from …

DRYD-1518: Associate a CSpace user to a SAML login using an ID from the assertion.

---

services/report/service/src/main/java/org/collectionspace/services/report/jasperreports/CSpaceReportScriptlet.java
services/report/service/src/main/java/org/collectionspace/services/report/jasperreports/DeurnArray.java

* Add deurn function for arrays
This is to support new reports [DRYD-1334](https://collectionspace.atlassian.net/browse/DRYD-1334) and [DRYD-1335](https://collectionspace.atlassian.net/browse/DRYD-1334). It allows us to deurn in the services layer rather than the database. 
* Pass an array in to the deurn fields
* See that it is deurned
@ray-lee I wanted to get this in first before doing the reports as I have a few thoughts/concerns on it first.
I opted to set the field to a List, but I'm still debating this. This is fine for groovy, but when using Rhino for the jasper expressions there isn't really …

Support for deurning arrays in reports

---

services/servicegroup/jaxb/src/main/resources/servicegroup_common.xsd
services/servicegroup/service/src/main/java/org/collectionspace/services/servicegroup/ServiceGroupResource.java
services/servicegroup/service/src/main/java/org/collectionspace/services/servicegroup/nuxeo/ServiceGroupDocumentModelHandler.java

* Add new endpoint /servicegroups/:group/tags
* Add servicetag query param to /servicegroups/:group
* Apply spotless
Jira: https://collectionspace.atlassian.net/browse/DRYD-1351
We want to be able to organize procedures on the Create New page into groups. In order to do this we added support for tagging procedures, but didn't update the API to support what tags exist and displaying record types which have a given tag. These changes add both of those to the ServiceGroupResource which allows us to finish the workflow in the ui.
* Rebuild and deploy collectionspace
* Test the new `/servicegroups/:group/tags` endpoint
* e.g. `curl -H "Accept: …

DRYD-1351: API For Supporting Create Page Update

---

services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_intent_to_repatriate.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_inventory_completion.jrxml

* Add parens to involved role condition
Jira: https://collectionspace.atlassian.net/browse/DRYD-1334
I added the involved role condition late and did not do it correctly initially, missing the parens to group the or together. ~~I think this may have also been the reason why I needed the distinct clause as well for that join, so that may be able to be removed~~. The distinct clause is needed for retrieving the first row. Could also be done with limit but didn't seem to differ much based on a quick test.
* If in an existing install: replace the `notice_of_intent_to_repatriate.jrxml` with the new file
* This can be done with the report ant task as well
``` …
```

Notice Intent to Repatriate: fix query for involved parties

---

pom.xml

Update the compiler to target Java 8
We've been running Java 8 in production for a while and with some of the dependency updates recently we've been able to target Java 8. Ideally we'd move to the latest version but since that will be a bigger target we're doing this for some better quality of life.
* Rebuild collectionspace with tenants enabled for integration testing
* Start collectionspace
* Run the integration tests for the services layer
None
No
@mikejritter built and …

Set compiler target to 1.8

---

services/common/src/main/cspace/config/services/tenants/fcart/fcart-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/materials/materials-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml

* Index new related link fields
* Index displayName for featuredCollection
Jira:
* https://collectionspace.atlassian.net/browse/DRYD-1455
* https://collectionspace.atlassian.net/browse/DRYD-1456
The related link group list is a new field for 8.1 which is meant for the public browser. This adds the field to the elastic index so it can be... indexed.
Likewise there was a request to have the Featured collection be clickable with the link bringing you to the search results on the featured collection. Since the filtering is normally done using a human readable name, this adds the displayName field to the index for featuredCollections so that it may be queried on.
**How should this be tested? Do these changes have associated …

Add relatedLinks, featuredCollection displayName to elastic index

---

services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_intent_to_repatriate.jrxml

* Switch to javascript templating
* Pull distinct acquisitions related to summary
* Coalesce for better null handling
* Adjust spacing for some fields
Jira: https://collectionspace.atlassian.net/browse/DRYD-1334
These are changes that came out of initial testing for the Notice of Intent to Repatriate report. Notably we had duplicating values; we now use distinct on the summary id for acquisitions to try and limit this. There will likely be some repeated data if multiple acquisitions have the same values but that is something which is still up for discussion. Likewise we are now using coalesce in order to prevent null arrays, and using filter when joining array values in order to remove null entries.
**How should this be …

Report: Notice of Intent to Repatriate QA

---

services/report/3rdparty/jasper-cs-report/src/main/resources/accessions.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/artwork_description.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/borrowing_receipt.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/box_list.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/condition.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/deaccessions.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/deed_of_gift.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/incoming_loan_letter.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_computed_location.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/obj_current_place_details.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/outgoing_loan_letter.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/referral.xml

* Adds descriptions to reports
Jira: https://collectionspace.atlassian.net/browse/DRYD-1431
This adds descriptions to reports which had placeholders. Note that this is only for older reports, not newer ones for 8.1.
* Build a clean install for CollectionSpace
* See that the reports have appropriate descriptions
None
No
Also no.

DRYD-1431: Add descriptions to reports

---

build.properties
cspace-ui/bonsai/build.properties
cspace-ui/botgarden/build.properties
cspace-ui/herbarium/build.properties
cspace-ui/lhmc/build.properties
cspace-ui/materials/build.properties
cspace-ui/publicart/build.properties

This updates the build.properties to be in line with the latest RC versions for the ui components
No jira.
This is required for cspace to build correctly.
* Rebuild collectionspace and ensure it succeeds
None
No
@mikejritter is building locally

Build RC Updates

---

services/report/3rdparty/jasper-cs-report/src/main/resources/Exhibition_List_Basic.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/inventory_consultation.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/inventory_consultation.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_intent_to_repatriate.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_intent_to_repatriate.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_inventory_completion.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/notice_of_inventory_completion.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/repatriation_request_consultation.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/repatriation_request_consultation.xml
services/report/3rdparty/jasper-cs-report/src/main/resources/summary_documentation_consultation.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/summary_documentation_consultation.xml

* Use objectproductionpeople for related culutres - summary; inventory
* Fix location for mni and afo counts - inventory
* Add collectors to description text - intent to repatriate
* Pull multiple involved parties - intent to repatriate
* Deurn objectproductionpeople - exhibition basic list
* Make header text more consistent for 8.1 reports
* Adjust header spacing and height for 8.1 reports
* Add 8.1 report descriptions
* https://collectionspace.atlassian.net/browse/DRYD-1598
* https://collectionspace.atlassian.net/browse/DRYD-1603
This has a few things which were missed in the previous PRs with report updates and some more changes after looking at the reports as a whole in order to add some more consistency to them. In …

8.1 Reports QA

---

services/report/3rdparty/jasper-cs-report/src/main/resources/full_obj_place.xml

* Add description to xml payload
Jira: https://collectionspace.atlassian.net/browse/DRYD-1431
The Full Object with Place Details report was missing a description.
* Build a clean collectionspace install with the public art profile enabled
* See that the Full Object with Place Details has the updated description
None
No
@mikejritter will test locally

Add description to full object with place report

---

services/report/3rdparty/jasper-cs-report/src/main/resources/repatriation_request_consultation.jrxml

* Use nagpraDetermGroup for cultures output 
Jira: https://collectionspace.atlassian.net/browse/DRYD-1512
There was confusion about which field should be used to populate the output of the cultures related to requsted objects. After some discussion we reached the conclusion that it should be from the NAGPRA extension, which is in the `nagpradetermgroup` table.
* Rebuild and deploy collectionspace with anthro enabled
* Create a Repatriation Request
* Create a related CollecionObject
* In the CollectionObject, populate the `Cultural determination` field under the `Repatriation and NAGPRA Compliance Information` section
* Search for Repatriation Requests …

Pull cultural determination from nagpra extension

---

services/report/3rdparty/jasper-cs-report/src/main/resources/contact_org.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/contact_person.jrxml

* Remove default value for csid
* Add no data section
* Allow queries with no where clauses
Jira: https://collectionspace.atlassian.net/browse/DRYD-1576
When testing the contact organization report we saw that it wasn't working properly when being run on search results. This was being caused by the default value for `csid` which was being used instead of the provided csid list. In addition, when no contact exists for an organization an empty report was being returned, which has been replaced by the `noData` section.
* Redeploy the tests
* Search for organizations
* Run the report on selected organizations
**Dependencies for merging? Releasing to …

Contact Organization Fix

---

services/report/3rdparty/jasper-cs-report/src/main/resources/full_obj_place.jrxml

* Update to aggregate all `collectionobjects_publicart_publicartcollections` for a collection object
Jira: https://collectionspace.atlassian.net/browse/DRYD-1662
This was a request which came in from Creative West for an update to the report. I opted to update the scripting language to js because the fields to be de-urned and we now have support for de-urning arrays. So we can join the array rather than the regex + string agg. I'm not actually sure which method is better but trying to be consistent with something.
* Rebuild and start collectionspace with the publicart profile enabled
* In the publicart profile
* Create a collectionobject
* Assign …

DRYD-1660: Aggregate collections for objects

---

services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/core/core-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/tenant-bindings-proto-unified.xml

This moves the report config for the new NAGPRA reports into the core and anthro tenant bindings. By doing this we ensure that the reports are only available for those tenants, as they are the only tenants with the procedures enabled for those reports.
Jira: https://collectionspace.atlassian.net/browse/DRYD-1687
In tenants other than core/anthro, the NAGPRA reports can be selected from the Tools > Reports interface. This has a modal which allows a user to select records to run the report on with a record type that does not exist in the tenant, and as such causes an error in the ui. Ideally we need error handling in the ui as well, but for the time being we've decided to fix things here for now.
**How should this be tested? …

DRYD-1687: Load NAGPRA reports in only core and anthro

---

.gitignore
services/common/src/main/java/org/collectionspace/services/common/security/CSpaceSaml2ResponseAuthenticationConverter.java
services/common/src/test/java/org/collectionspace/services/common/test/AbstractSecurityTestBase.java
services/common/src/test/java/org/collectionspace/services/common/test/SecurityUtilsTest.java
services/config/pom.xml
services/config/src/main/java/org/collectionspace/services/common/config/AbstractConfigReaderImpl.java
services/config/src/test/java/org/collectionspace/services/common/config/ServicesConfigReaderImplTest.java

While working on some of the SAML SSO JIRA tickets such as [DRYD-1702](https://collectionspace.atlassian.net/browse/DRYD-1702), I wrote a number of unit tests for testing CollectionSpace's handling of incoming SAML assertions with configured assertion probes. I think these tests are of general value for avoiding regressions, so they are present in this pull request. I also made some relatively minor changes that are also useful; for instance, adding `.mvn` to `.gitignore` so that developers can store local maven configurations without accidentally sending them to the git repository.
I did most of the work in this pull request while investigating a SAML SSO related issue …

SAML SSO unit tests etc.

---

pom.xml
services/JaxRsServiceProvider/pom.xml

Our build had `git-commit-id-plugin` in the topmost `pom.xml` file from which all other `pom.xml` files inherit. This plugin' reads the latest git commit and stores it in a file `git.properties` that is read by the `systeminfo` service. See for instance; 
this shows the version of CSpace services running comes from commit `a7af564` (the<build> tag).
However, because of this inheritance structure the `git-commit-id-plugin` was being run 217 times during builds, even builds that don't need this number. This unnecessary extra work added tens of seconds to build times. 
This change removes the `git-commit-id-plugin` from the topmost `pom.xml` and places it instead in the `JaxRsServiceProvider` project. The latter is where the ultimate WAR file used to deploy Cspace …

DRYD-1712/DRYD-1715: only run `git-commit-id-plugin` once

---

pom.xml

The `maven-antrun-plugin` was running a goal `check-env-vars` once for every child project within the `services` multi-module project. Besides being a redundant check--the env cannot change while maven is executing--and besides being a deploy-only necessity, it also added many seconds to compile times. This PR changes the build process to only run `check-env-vars` once per compile cycle, saving ~5 seconds of compile time.
Addresses JIRA ticket [DRYD-1716](https://collectionspace.atlassian.net/browse/DRYD-1716)
This is a build-level change so there are no unit tests. It can be tested by running commonly-used maven commands and verifying they are behaving …

DRYD-1716: set the antrun plugin that runs check-env-vars to <inherited>false</inherited>

---

services/report/3rdparty/jasper-cs-report/src/main/resources/full_obj_place.jrxml

This protects against the `collection` field being null by coalescing with an empty array. 
Jira: https://collectionspace.atlassian.net/browse/DRYD-1759
Recently we made a change to aggregate the `collection` field in the full object with place details report. This was done without any guard around the value being null which could occur if no collections were added to an object. This caused a null error to be created when the string concatenation was being done (using `join`).
* Deploy the test with the publicart profile enabled
* Create an object without anything in the `collection` field
* Run the `Full Object with Place Details` report
* I'm not sure …

DRYD-1759: Null Error in Full Place Report

---

common-lib/pom.xml

Re-adds the aspectj dependencies when deploying cspace
Related to - Jira: https://collectionspace.atlassian.net/browse/DRYD-1742
When initially reworking the dependency copies, I opted to remove the aspectj dependencies thinking we could add them into the gateway. However when trying this I found that the classes were still not being loaded because some of the other dependencies in the `${TOMCAT}/lib` directory. We'll have to update the two builds later on because it's there are some other issues starting to appear from the current build.
Redeploy collectionspace as well as the cspace-public-gateway to the same Tomcat …

Add aspectj dependencies back into deployment

---

build.properties

This updates the build property for `cspace.ui.build.branch` to be `develop`. 
No jira.
This will allow our dev deployments to build the latest version of the cspace-ui, which is now on the `develop` branch.
* Set the `CSPACE_UI_BUILD` env var to true
* Rebuild collection space
* Check the commit is the same as `develop`'s `head`
This impacts the build which is worth noting. When releasing to production, we'll want to ensure this is actually `main` (or maybe it should use the release tag instead).
No
**Did someone actually run …

Update UI Build Branch

---

cspace-ui/anthro/build.properties
cspace-ui/bonsai/build.properties
cspace-ui/botgarden/build.properties
cspace-ui/fcart/build.properties
cspace-ui/herbarium/build.properties
cspace-ui/lhmc/build.properties
cspace-ui/materials/build.properties
cspace-ui/publicart/build.properties

This updates the build property for `tenant.ui.profile.plugin.build.branch` to be `main`. 
No jira.
This will allow our dev deployments to build the latest version of the cspace profile plugins. They are fairly low churn so they've mostly only had one branch workflows which is why they use `main` and not `develop`
* Set the `CSPACE_UI_BUILD` env var to true
* Rebuild collection space
* Check the commit is the same as `main`
All repositories will need to be updated. Only a few have been so far, but it's a fairly quick change to make.
**Has the application documentation been updated for these …

Update build branch for ui plugins

---

services/report/3rdparty/jasper-cs-report/src/main/resources/coreIntake.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanIn.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreLoanOut.jrxml
services/report/3rdparty/jasper-cs-report/src/main/resources/coreObjectExit.jrxml

This updates the `co.fieldcollectionplace` column to be a join on `collectionobjects_common_fieldcollectionplaces` as the field was changed to be repeating 
Jira: https://collectionspace.atlassian.net/browse/DRYD-1795
When this field was migrated to be repeating, we neglected to update reports which used it. This caused the reports to fail when the sql would fail to run in the database.
* Rebuild and deploy CollectionSpace
* Create a CollectionObject with a `Field collection place` (underneath the `Object Collection Information` panel)
* For Intake:
* Create an Intake with an entry date, return date, and entry note
* Run the `Intake Ethnographic Object …

DRYD-1795: Fix 500 Error for Ethnographic Object Reports

---

services/common/src/main/cspace/config/services/tenants/anthro/anthro-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/bonsai/bonsai-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/lhmc/lhmc-tenant-bindings.delta.xml
services/common/src/main/cspace/config/services/tenants/materials/materials-tenant-bindings.delta.xml

Adds the `publishedRelatedLinkGroupList` to all Elasticsearch bindings
Jira: https://collectionspace.atlassian.net/browse/DRYD-1455
This was supposed to be in all profiles. It was only added to core, fcart, and whatever profiles don't override the inherited bindings. This adds the group to the bindings for all other profiles.
* Rebuild collectionspace and deploy with the cspace-public-gateway
* Start Elasticsearch
* Edit the `nuxeo.properties` in your collectionspace installation and set `elasticsearch.enabled` to `true`
* Start CollectionSpace
* Create a CollectionObject with the `Published related link` filled out
* ...continue testing in the public …

Add publishedRelatedLinkGroupList to all ES bindings

---

build.xml
src/main/resources/db/postgresql/update_userid_function.sql

This PR adds:
- A SQL script `services/src/main/resources/db/postgresql/update_userid_function.sql`
- A new `ant` target `create_update_userid_db_function` that calls this SQL script to create the `update_userid` function in the database
This PR updates:
- `ant deploy` to put `update_userid_function_sql` in  `$CSPACE_JEESERVER_HOME/cspace/services/db/postgresql` 
- `ant create_db` to run this script and create the `update_userid` function.
On initial `ant create_db`, the function will be added to the database. If one only wants to create the function and not call any other ant targets, `ant create_update_userid_db_function` will do that. One could also run the SQL script.
Jira ticket: …

DRYD-1747: Add update_userid function to database
